const categories={visual:'图像与视觉',writing:'写作与表达',knowledge:'阅读与判断',building:'构建与工具',personal:'个人创作'};
const projects=d.projects.filter(x=>x.visibility==='public'),skills=d.skills.filter(x=>x.visibility==='public');
const savedPositions=new Map();let previousCatalogue='';
function imagePath(raw){return raw?.startsWith('assets/')?'../'+raw:raw?'../'+raw:''}
function visualFor(item,isProject){const v=d.profiles[item.id]?.visual||d.skillImages[item.id];return isProject?{image:item.image,caption:item.imageAlt}:v?.image?{image:v.image,caption:v.caption||v.imageAlt}:null}
function preview(item,isProject){const v=visualFor(item,isProject);return v?`<img src="${esc(imagePath(v.image))}" alt="${esc(v.caption||item.title)}">`:`<span class="type-cover" aria-label="类型字标，非作品样例">${esc(categories[item.category]?.slice(0,2)||'方法')}<small>方法条目</small></span>`}
function bindImages(root){root.querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>{const dialog=document.querySelector('dialog');dialog.querySelector('img').src=b.dataset.image;dialog.querySelector('img').alt=b.querySelector('img').alt;dialog.showModal()})}
function backpages(){const back=document.querySelector('#print-back');if(back){back.insertAdjacentHTML('afterbegin',`<div class="annotated-proof">${shot('exhibition-hub-ui-collage.webp','设计样张全图，编号对应下方批注')}<span class="pin p1">01</span><span class="pin p2">02</span></div><div class="proof-pieces"><figure><div class="crop crop-type"><img src="../assets/exhibition-hub-ui-collage.webp" alt="原图标题局部"></div><figcaption>01 / 字体与阅读方向 · 原图局部</figcaption></figure><figure><div class="crop crop-card"><img src="../assets/exhibition-hub-ui-collage.webp" alt="原图编辑台卡片局部"></div><figcaption>02 / 卡片与色块 · 原图局部</figcaption></figure></div>`);bindImages(back)}const detail=document.querySelector('.ink .actions details');if(detail){detail.querySelector('summary').insertAdjacentHTML('afterend',`<div class="ink-back-image">${shot('inkpanda-editor.png','编辑器原图：正文与人物在同一空间')}<span>正文在中间，人物在手边。</span></div>`);bindImages(detail)}}
function catalogue(){const hash=location.hash.slice(1);backpages();if(!hash.startsWith('catalogue')){previousCatalogue='';const selection=document.querySelector('.selection');selection?.querySelector('.intro').insertAdjacentHTML('afterend',`<div class="catalogue-entry"><a href="#catalogue/works">看满内容作品目录 <b>${projects.length} 件 ↗</b></a><a href="#catalogue/visual">看完整 Skill 分类 <b>${skills.length} 项 ↗</b></a></div>`);return}
const [,requested='works',chosen='']=hash.split('/');const category=requested==='works'||categories[requested]?requested:'works',isProject=category==='works';const items=isProject?projects:skills.filter(s=>s.category===category);const selected=items.find(x=>x.id===chosen)||items[0];const oldRail=document.querySelector('.catalogue-rail');if(oldRail&&previousCatalogue)savedPositions.set(previousCatalogue,oldRail.scrollTop);previousCatalogue=category;
app.innerHTML=`<nav class="route"><a href="#index">← 返回样板比较</a><a href="../index.html#works">原场刊保持不变 ↗</a></nav><div class="catalogue-heading"><div><p class="eyebrow">LOKI / 全量目录试装</p><h1>${isProject?'作品节目单。':'制作手册。'}</h1></div><p>${isProject?`${projects.length} 件公开作品，选一件展开。`:`${skills.length} 项公开方法，按五类查找。`}<br><small>本轮先检验满内容排列，详情为目录摘要。</small></p></div><nav class="category-nav" aria-label="作品与 Skill 分类"><a href="#catalogue/works" ${isProject?'aria-current="page"':''}>作品 <b>${projects.length}</b></a>${Object.entries(categories).map(([key,name])=>`<a href="#catalogue/${key}" ${category===key?'aria-current="page"':''}>${name}<b>${skills.filter(s=>s.category===key).length}</b></a>`).join('')}</nav><div class="catalogue-spread"><section class="catalogue-rail" aria-label="${isProject?'作品':'Skill'}目录">${items.map((item,i)=>`<a class="catalogue-item" href="#catalogue/${category}/${item.id}" ${selected.id===item.id?'aria-current="true"':''}>${preview(item,isProject)}<span><small>${String(i+1).padStart(2,'0')} / ${esc(isProject?item.tag:item.form)}</small><b>${esc(item.title)}</b><p>${esc(item.summary)}</p></span><i>↗</i></a>`).join('')}</section><section class="catalogue-detail" aria-label="选中条目详情">${selectionDetail(selected,isProject,category,items)}</section></div>`;
document.body.dataset.page='catalogue';const rail=document.querySelector('.catalogue-rail');rail.scrollTop=savedPositions.get(category)||0;rail.addEventListener('scroll',()=>savedPositions.set(category,rail.scrollTop));bindImages(app);document.querySelector('.return-directory').onclick=()=>{const row=rail.querySelector('[aria-current]');row.focus({preventScroll:true});row.scrollIntoView({block:'nearest',behavior:'instant'})};if(chosen&&innerWidth<=700)document.querySelector('.catalogue-detail').scrollIntoView({block:'start',behavior:'instant'});
}
function selectionDetail(item,isProject,category,items){const v=visualFor(item,isProject),profile=d.profiles[item.id],gh=d.github[item.id];const link=isProject?item.publicLink:gh;const example=item.id==='inkpanda'?'ink':item.id==='visual-directions'?'visual':item.id==='ebook-workflow'?'build':null;const i=items.indexOf(item);return `<div class="detail-topline"><small>${String(i+1).padStart(2,'0')} / ${items.length}</small><button class="return-directory">收回 · 回到所选条目 ↑</button></div><h2>${esc(item.title)}</h2><p class="detail-summary">${esc(item.summary)}</p>${v?`<button class="image detail-preview" data-image="${esc(imagePath(v.image))}" aria-label="放大图片"><img src="${esc(imagePath(v.image))}" alt="${esc(v.caption||item.title)}"><span>查看原图 ↗</span></button><p class="note">${esc(v.caption||'已有展示素材')}</p>`:`<div class="no-sample"><b>${esc(categories[item.category])}</b><p>对应样例尚未收录，先看方法用途。</p></div>`}<details><summary>看用途与公开边界 ＋</summary><p>${esc(isProject?item.proof:profile?.realResult||d.flows[item.id]?.join(' → ')||item.summary)}</p><small>${esc(isProject?item.verification?.note||item.status:profile?.limitations||item.form)}</small></details>${example?`<a class="out" href="#${example}">试开已设计的完整内页 <span>↗</span></a>`:''}${link&&(isProject||gh.kind!=='profile')?external(link.href,link.label||'查看相关源码'):`<p class="note">${isProject?'当前展示站内案例资料。':'暂无已确认的专属仓库入口，不用个人主页替代。'}</p>`}<p class="note">${esc(isProject?item.status:gh?.note||'')}</p><div class="item-navigation">${i>0?`<a href="#catalogue/${category}/${items[i-1].id}">← 上一件</a>`:'<span>本类第一件</span>'}${i<items.length-1?`<a href="#catalogue/${category}/${items[i+1].id}">下一件 →</a>`:'<span>本类最后一件</span>'}</div>${isProject?`<a class="case-cta" href="../projects/${item.id==='loki-ebook-converter'?'ebook-converter':item.id}.html">介绍看完了？打开这件作品的完整案例页 <span>项目故事 ↗</span></a>`:''}`}
addEventListener('hashchange',catalogue);catalogue();
