const volumes={visual:['看','图像、海报与视觉系统','#d8ed59'],writing:['写','选题、文章与表达','#ffa1c2'],knowledge:['想','阅读、证据与判断','#b8c8ff'],building:['做','构建、工具与工作流','#9bdde9'],personal:['藏','个人创作与长期偏好','#ff965e']};
let directoryOrigin='';
function directory(){const parts=location.hash.slice(1).split('/');if(parts[0]!=='catalogue')return;const category=parts[1]||'works',isWork=category==='works';if(!isWork&&!categories[category])return;const items=isWork?projects:skills.filter(s=>s.category===category),selected=items.find(s=>s.id===parts[2]);document.body.dataset.material=isWork?'poster-directory':'volume-directory';
const head=`<nav class="route"><a href="#index">← 返回样板</a><div><a href="#catalogue/works" ${isWork?'aria-current="page"':''}>作品节目单</a><a href="#catalogue/visual" ${!isWork?'aria-current="page"':''}>Skill 制作手册</a></div></nav><div class="directory-masthead"><div><p class="eyebrow">LOKI / ${isWork?'作品节目单':'SKILL 制作手册'}</p><h1>${isWork?'想法，做出来。':'方法，带走用。'}</h1></div><p>Loki · AI 内容创作者 / Vibe coder<br><small>${isWork?'产品、工具与个人系统，十一件公开作品。':'图像、写作、阅读、构建与个人创作，五册制作手册。'}</small></p><b class="directory-count">${isWork?'11':'22'}<small>${isWork?'件作品':'项方法'}</small></b></div>`;
const itemDetail=item=>`<section class="directory-insert" id="open-${item.id}" aria-label="${esc(item.title)}详情">${selectionDetail(item,isWork,category,items)}</section>`;
if(isWork){const featured=items.filter(p=>p.group==='flagship'),others=items.filter(p=>p.group!=='flagship');const descriptions={'interface-system':'把每天使用的 AI 工具，改成自己的工作空间。','perspective-distillation':'从公开材料里提炼判断，再用新问题检查。','inkpanda':'让正文、人物与前情，留在同一个长篇工作台。'};app.innerHTML=head+`<div class="lineup-sheet"><div class="lineup-caption"><span>代表作品 / 三条创作主线</span><b>LOKI — SELECTED WORKS</b></div><div class="headline-acts">${featured.map((p,i)=>`<article class="lineup-act"><a class="lineup-link" id="entry-${p.id}" href="#catalogue/works/${p.id}" aria-expanded="${selected?.id===p.id}"><span class="act-no">0${i+1}</span><span class="act-title"><small>${esc(p.tag)}</small><h2>${esc(p.title)}</h2><p>${esc(descriptions[p.id]||p.summary)}</p></span><span class="act-open">打开作品 <b>↗</b></span></a>${selected?.id===p.id?itemDetail(p):''}</article>`).join('')}</div><div class="encore-label"><b>还有这些，一直在做</b><span>其他公开作品 / ${others.length} 件</span></div><div class="supporting-acts">${others.map((p,i)=>`<article><a class="lineup-link supporting-link" id="entry-${p.id}" href="#catalogue/works/${p.id}" aria-expanded="${selected?.id===p.id}"><span class="act-no">0${featured.length+i+1}</span><span><h2>${esc(p.title)}</h2><p>${esc(p.summary)}</p></span><span class="act-open">打开 <b>↗</b></span></a>${selected?.id===p.id?itemDetail(p):''}</article>`).join('')}</div><footer class="lineup-footer"><b>台下看演出，散场继续做。</b><span>Loki / AI 内容创作者 · Vibe coder</span></footer></div>`;app.querySelector('.directory-masthead h1').textContent='作品节目单'}
else{app.innerHTML=head+`<div class="volume-shelf">${Object.entries(volumes).map(([key,[glyph,description,color]],i)=>`<section class="volume ${key===category?'volume-open':''}" style="--volume:${color}"><a class="volume-cover" href="#catalogue/${key}" ${key===category?'aria-current="page"':''}><small>制作手册 / 0${i+1}</small><strong>${glyph}</strong><h2>${categories[key]}</h2><p>${description}</p><span>${skills.filter(s=>s.category===key).length} 项方法 ${key===category?'／ 已展开':'／ 打开 ↗'}</span></a>${key===category?`<div class="volume-pages"><div class="volume-head"><b>${categories[key]}</b><small>选择方法，抽出内页</small></div>${items.map((s,j)=>`<article class="method-entry"><a id="entry-${s.id}" href="#catalogue/${category}/${s.id}" aria-expanded="${selected?.id===s.id}"><span class="method-index">${String(j+1).padStart(2,'0')}</span><span><h3>${esc(s.title)}</h3><p>${esc(s.summary)}</p><small>${esc(s.tags.join(' / '))}</small></span><b>抽出 ↗</b></a>${selected?.id===s.id?itemDetail(s):''}</article>`).join('')}</div>`:''}</section>`).join('')}</div>`}
bindImages(app);app.querySelectorAll('.lineup-link,.method-entry>a').forEach(a=>a.addEventListener('click',()=>{directoryOrigin=a.id}));const close=app.querySelector('.return-directory');if(close)close.onclick=()=>{directoryOrigin='entry-'+selected.id;location.hash='catalogue/'+category};if(selected)requestAnimationFrame(()=>document.querySelector('.directory-insert').scrollIntoView({block:'nearest',behavior:'instant'}));else if(directoryOrigin){const anchor=document.getElementById(directoryOrigin);if(anchor)requestAnimationFrame(()=>{anchor.focus({preventScroll:true});anchor.scrollIntoView({block:'center',behavior:'instant'})});directoryOrigin=''}
}
addEventListener('hashchange',directory);directory();
