function material(){
 const route=location.hash.slice(1)||'index';document.body.dataset.material=route.startsWith('catalogue/works')?'programme':route;
 const selection=document.querySelector('.selection');if(selection){selection.insertAdjacentHTML('afterbegin','<div class="tour-strip"><b>LOKI / OPEN STUDIO</b><span>一件产品、一套方法、一份制作背页</span><i>VOL. 01</i></div>');selection.insertAdjacentHTML('beforeend','<div class="edition-edge"><b>看完散场，回去接着做。</b><span>三个样板 / 由你翻开</span></div>')}
 const inkDetails=document.querySelector('.ink .actions details');if(inkDetails){inkDetails.classList.add('pullout');const summary=inkDetails.querySelector('summary');summary.innerHTML='<span><small>INKPANDA / 制作背页</small><b>抽出制作背页</b></span><i>↓</i>';const inner=document.createElement('div');inner.className='pullout-leaf';while(summary.nextSibling)inner.append(summary.nextSibling);inkDetails.append(inner);const close=document.createElement('button');close.className='fold-back';close.textContent='收回背页 ↑';close.onclick=()=>{inkDetails.open=false;summary.focus()};inner.append(close);inkDetails.addEventListener('toggle',()=>{summary.querySelector('b').textContent=inkDetails.open?'制作背页已展开':'抽出制作背页';summary.querySelector('i').textContent=inkDetails.open?'↑':'↓'})}
 const build=document.querySelector('.build');if(build){const manual=build.querySelector('.manual');manual.id='conversion-back';manual.hidden=true;const front=document.createElement('section');front.className='conversion-front';front.innerHTML=`<div><small>正面 / 做成的工具</small><h2>转换这件事，<br>留一个简单入口。</h2><p>先看做出来的工具，再翻到背面看它是怎么攒起来的。</p><button class="turn-manual" aria-expanded="false" aria-controls="conversion-back">翻到制作说明 <b>↗</b></button></div>${shot('ebook-app-home.png','电子书转换器真实首页')}`;manual.before(front);const bar=document.createElement('div');bar.className='manual-back-label';bar.innerHTML='<span>背面 / 输入 → 处理 → 带走</span><button class="fold-back">翻回工具正面 ↶</button>';manual.prepend(bar);front.querySelector('button').onclick=()=>{front.hidden=true;manual.hidden=false;front.querySelector('button').setAttribute('aria-expanded','true');bar.querySelector('button').focus({preventScroll:true})};bar.querySelector('button').onclick=()=>{manual.hidden=true;front.hidden=false;front.querySelector('button').setAttribute('aria-expanded','false');front.querySelector('button').focus({preventScroll:true})};bindImages(front)}
 const title=document.querySelector('.catalogue-heading h1');if(title)title.textContent=title.textContent.replace(/。$/,'');
 if(route.startsWith('catalogue/works')){document.querySelector('.catalogue-spread').classList.add('programme-spread');document.querySelectorAll('.catalogue-item').forEach((item,i)=>{item.dataset.number=String(i+1).padStart(2,'0')});}
}
addEventListener('hashchange',material);material();
