function perspectiveCase(){if(location.hash!=='#catalogue/works/perspective-distillation')return;const panel=document.querySelector('.directory-insert');if(!panel)return;const top=panel.querySelector('.detail-topline'),next=panel.querySelector('.item-navigation'),story=document.createElement('article');story.className='perspective-story';story.innerHTML=`
<header class="perspective-intro"><small>人物视角蒸馏 / Loki 的人物判断实验</small><h2>我喜欢她的表达。<br>然后呢，能学到什么？</h2><p>有些人的访谈和作品，我会看好几遍。喜欢她怎么说是一回事，我还想知道，换个没见过的问题，她会先想什么？所以就有了这个项目。</p><p>我把公开材料整理成方法，再让模型做新题，看看换个场景还管不管用。现在有 13 个人物档案，先拿刘恋这条线给你看一道题，其他几个人也可以在上面切换。</p></header>
<section class="case-question"><div class="case-label"><b>01</b><span>先看一道题</span></div><h3>宣传卡写得漂亮，<br>就能叫【嘉宾金句】吗？</h3><p>假设节目组要发一条预告。卡片上有一句好话，但谁说的还没核实：可能是嘉宾，也可能是主持人，甚至只是编辑起的标题。完整音频暂时听不到。</p><p class="question-prompt">如果让这个人物判断模型处理，它会建议制作团队怎么办？</p><small>已有内部测试题的简述。虚构情境，不是刘恋的真实经历。</small><details class="answer-reveal"><summary>看看当时怎么答的 <b>↓</b></summary><div class="answer-steps"><div><b>先别替这句话认主人</b><p>把嘉宾原话、主持人口播、编辑标题分开。还没确认归属，就先标待核，不加引号。</p></div><div><b>预告可以继续做</b><p>先用核实过的主题，或者清楚标注【节目编辑文案】。同时回听音频、查字幕和脚本，把说话人核对清楚。</p></div><div><b>发错了，也得改回来</b><p>发现归属不对，就撤换并说明更正。不能因为已经传开了，就将错就错。</p></div></div><p class="case-note">以上是已有 AI 答卷的编辑摘要，不是刘恋原话。这一题看的是材料归属和处理顺序，不是模仿她的语气。</p></details></section>
<section class="case-material"><div class="case-label"><b>02</b><span>这套方法从哪里来</span></div><h3>先把【我喜欢她】<br>和【材料能证明什么】分开。</h3><div class="material-spread"><figure>${shot('perspective-liulian-evidence-sheet-01.png','刘恋线公开节目片段帧采样表')}<figcaption>已有公开节目片段采样。用于回看材料，不是上面那道测试题的现场。</figcaption></figure><div><p>我整理了访谈、舞台、文字和创作材料。本人怎么讲自己、旁人怎么评价、我从中推出来什么，要分别留下。</p><p>这张图对应的近期片段来自粉丝剪辑。它能帮我观察这一段怎么接话，但只有片段，还不足以说明她平时一直这样说话。</p><p>完整字幕和连续音频没拿到的地方，缺口就留着。不能因为喜欢一个人，便把证据往满了写。</p></div></div></section>
<section class="case-process"><div class="case-label"><b>03</b><span>我具体做了什么</span></div><h3>把一句【很像她】，拆开检查。</h3><div class="process-notes"><article><small>整理材料</small><h4>这是谁说的？</h4><p>原话留下出处；自述、他人观察和我的推断分开。剪辑片段不能当成完整对话。</p></article><article><small>写成方法</small><h4>她做了哪一步？</h4><p>记录当时的任务、怎么接住问题、怎样修改、何时不再追问。少用一个人格标签把事情盖过去。</p></article><article><small>拿新题检查</small><h4>换个问题还管用吗？</h4><p>旧材料和测试题分开放。看 AI 在新情境里怎么选、怎么停，不把复述素材当作通过。</p></article></div></section>
<section class="case-test"><div class="case-label"><b>04</b><span>试过以后，留下了什么</span></div><h3>有答对的，也有要返工的。</h3><p>上面这题的内部复核记录认为，答卷分清了说话人、编辑文案和待核内容，也给出了核对期间继续做预告的办法。</p><p>同一轮还有一道题：能不能把一次即兴回应，写成处理所有冲突的固定方法？首轮答卷超过字数上限，后来单独压缩重跑。原答卷也保留了。</p><aside><b>这能说明多少？</b><p>目前能看到的是这套方法在几道虚构题里的表现。评分来自项目内部，不能当作第三方准确率，也不能证明 AI 真的成了某个人。</p></aside></section>
<footer class="case-ending"><h3>我想留下的，<br>是能拿去做事的判断。</h3><p>我还会继续往里补材料，碰到答偏的就留下来，看看是材料不够，还是方法写得太满。现在这套只在我本地跑，先给你看做到哪儿了。</p><a class="out" href="#catalogue/knowledge/judgment">看看判断蒸馏方法 <span>站内 →</span></a><details><summary>材料范围与公开说明 ＋</summary><p>本页根据已有公开案例、刘恋线的来源规则、陌生题答卷及内部报告整理。没有在本轮重新跑评测。人物本人未被表示为参与、认可或授权本项目；不推断未公开的私人关系，不将研究模型当作真人替身。</p><p>节目采样是受限的片段观察；上述测试题是虚构情境。两者分别展示，不把节目截图当作测试答案的直接证据。</p></details></footer>`;panel.replaceChildren(top,story,next);bindImages(story)}
function dressPerspective(){
 const intro=document.querySelector('.perspective-intro');
 if(!intro||intro.querySelector('.backstage-art'))return;
 const copy=document.createElement('div');copy.className='backstage-copy';
 while(intro.firstChild)copy.append(intro.firstChild);
 const art=document.createElement('figure');art.className='backstage-art';
 art.innerHTML='<img src="../assets/panda-backstage-reader-v1.png" width="1536" height="1024" alt="Loki 小熊猫戴着耳机，在演出后台用放大镜查看卡片的概念插画"><figcaption>喜欢归喜欢，材料还得仔细看。</figcaption>';
 intro.append(copy,art);
}
addEventListener('hashchange',()=>{perspectiveCase();dressPerspective()});perspectiveCase();dressPerspective();
