const app=document.querySelector('#app'),d=window.bookData;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shot=(file,alt,cls='')=>`<button class="image ${cls}" data-image="../assets/${file}" aria-label="放大：${alt}"><img src="../assets/${file}" alt="${alt}"><span>查看原图 ↗</span></button>`;
const external=(url,label)=>`<a class="out" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} <span>外部 ↗</span></a>`;
const nav=id=>`<nav class="route"><a href="#index">← 收回 · 三个样板</a><div>${[['ink','01 产品'],['visual','02 视觉'],['build','03 构建']].map(([key,label])=>`<a href="#${key}" ${key===id?'aria-current="page"':''}>${label}</a>`).join('')}</div></nav>`;
function index(){return `<section class="selection"><p class="eyebrow">LOKI / 展示方式试装 01</p><h1>打开以后，<br>还得有点意思。</h1><p class="intro">同一本场刊，三种内页。选一件，试试怎么展开。</p><div class="samples"><a href="#ink" class="sample ink-mini"><small>01 / 产品 · INKPANDA</small><strong>把长篇<br>接着写。</strong><img src="../assets/inkpanda-editor.png" alt="InkPanda 真实编辑器"><span>打开创作工作台 ↗</span></a><a href="#visual" class="sample visual-mini"><small>02 / SKILL · 视觉方向</small><strong>同一份内容<br>换一种看法。</strong><img src="../assets/exhibition-hub-ui-collage.webp" alt="Loki Hub 视觉设计稿"><span>抽出设计样张 ↗</span></a><a href="#build" class="sample build-mini"><small>03 / 方法 · 电子书转换</small><strong>复杂的，<br>留在后台。</strong><div class="file-mark">EPUB <i>↗</i></div><span>翻看制作说明 ↗</span></a></div><p class="note">只比较内页设计，不替换现有首页。产品状态与链接沿用场刊记录，未在本轮重新核验。</p></section>`}
function ink(){const p=d.projects.find(p=>p.id==='inkpanda');return `${nav('ink')}<article class="ink"><div class="title-row"><div><p class="eyebrow">01 / INKPANDA · AI 长篇写作</p><h1>故事往前走，<br><em>前情别掉队。</em></h1></div><p class="lede">${esc(p.summary)}</p></div><section class="workstation"><aside class="scene-list"><small>这张工作台，怎么读</small>${['先看全貌','接着写正文','把人物带回来'].map((s,i)=>`<button data-scene="${i}" aria-pressed="${i===0}"><b>0${i+1}</b>${s}<span>↗</span></button>`).join('')}<p>真实界面导览<br>不是在线编辑器</p></aside><div class="screen-area">${shot('inkpanda-editor.png','InkPanda 真实编辑器','editor')}<div class="scene-caption" aria-live="polite"><b id="scene-title">写作，不只剩一个输入框。</b><p id="scene-copy">正文、章节和右侧的人物上下文，都在这张真实界面里。</p></div></div></section><footer class="actions"><details><summary>翻到制作背页 <span>＋</span></summary><p>${esc(p.proof)}</p><p>${esc(p.systemEvidence[0].value)}</p><small>${esc(p.verification.note)}。沿用 ${esc(p.verification.checkedAt)} 记录。</small></details>${external(p.publicLink.href,'打开 InkPanda')}<small>完整体验需要登录 · 登录后交互待复核</small></footer></article>`}
function visual(){const p=d.profiles['visual-directions'],g=d.github['visual-directions'];return `${nav('visual')}<article class="visual"><div class="visual-caption"><p class="eyebrow">02 / 视觉方向设计</p><h1>风格，<br>不止换色。</h1><p>同一份内容，阅读顺序和画面重心也得重新想。</p><div class="edition-number">01<small>/ 已收录样张</small></div><button class="flip" aria-expanded="false">翻到样张背面 ↗</button><p class="note">Loki Hub · 城市编辑台<br>视觉设计稿，非运行截图</p>${external(g.href,g.label)}<small>${esc(g.note)}</small></div><div class="print-table"><span class="paper-label">LOKI / DESIGN PROOF</span><div id="print-front">${shot('exhibition-hub-ui-collage.webp','Loki Hub 城市编辑台视觉设计稿')}<p>点样张可放大，保留原图比例。</p></div><section id="print-back" hidden><small>样张背面 / 我的取舍</small><h2>先决定<br>让人看见什么。</h2><ol><li><b>观看顺序</b><p>大标题先说出主题，小的编辑台卡片随后进入视线。</p></li><li><b>版面关系</b><p>斜向色块、竖排标题和倾斜卡片，改变画面重心。</p></li><li><b>不能省的判断</b><p>${esc(p.limitations)}</p></li></ol><p class="note">${esc(p.evidenceStatus)}</p></section></div></article>`}
function build(){const p=d.projects.find(p=>p.id==='loki-ebook-converter'),g=d.github['ebook-workflow'];return `${nav('build')}<article class="build"><div class="build-heading"><p class="eyebrow">03 / 电子书转换工作流</p><h1>拖进来。<br><em>把书带走。</em></h1><p>${esc(p.summary)}</p><span class="format-stamp">EPUB<br>↕<br>MOBI</span></div><section class="manual"><div class="manual-tabs" aria-label="制作说明章节">${['输入','处理','带走'].map((s,i)=>`<button data-step="${i}" aria-pressed="${i===0}"><b>0${i+1}</b>${s}</button>`).join('')}</div><div class="manual-body"><div class="manual-copy" aria-live="polite"><small>制作说明 / 非现场转换演示</small><h2 id="step-title">入口，少一道门槛。</h2><p id="step-copy">把电子书拖进应用。先把复杂能力收在后台，让入口保持简单。</p><div class="step-note">${esc(g.note)}</div></div><figure>${shot('ebook-app-home.png','电子书转换器真实首页')}<figcaption>相关产品 / 真实桌面应用首页</figcaption></figure></div></section><footer class="build-footer">${external(g.href,'查看产品源码')}${external(p.publicLink.href,'前往下载页')}<details><summary>版本与核验记录 ＋</summary><p>${esc(p.tag)} · ${esc(p.verification.note)}</p><small>沿用 ${esc(p.verification.checkedAt)} 记录，本轮不下载、不安装。</small></details></footer></article>`}
function render(){const id=location.hash.slice(1)||'index';app.innerHTML=({ink,visual,build}[id]||index)();document.body.dataset.page=id;app.querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>{const modal=document.querySelector('dialog');modal.querySelector('img').src=b.dataset.image;modal.querySelector('img').alt=b.querySelector('img').alt;modal.showModal()});app.querySelector('.flip')?.addEventListener('click',e=>{const on=e.currentTarget.getAttribute('aria-expanded')!=='true';e.currentTarget.setAttribute('aria-expanded',on);e.currentTarget.textContent=on?'翻回设计样张 ↶':'翻到样张背面 ↗';document.querySelector('#print-front').hidden=on;document.querySelector('#print-back').hidden=!on});
const scenes=[['写作，不只剩一个输入框。','正文、章节和右侧的人物上下文，都在这张真实界面里。'],['正文留在中间。','章节列表在左侧，写作工具在上方，当前正文保持独立阅读区域。'],['人物放在手边。','右侧可以看到本章目标和涉及人物。这张图展示界面，不代表本轮完成了功能复核。']];app.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{app.querySelectorAll('[data-scene]').forEach(x=>x.setAttribute('aria-pressed',x===b));const n=+b.dataset.scene;document.querySelector('.screen-area').dataset.scene=n;document.querySelector('#scene-title').textContent=scenes[n][0];document.querySelector('#scene-copy').textContent=scenes[n][1]});
const steps=[['入口，少一道门槛。','把电子书拖进应用。先把复杂能力收在后台，让入口保持简单。'],['复杂能力，交给后台。','工作流把 Calibre 的转换能力包装成批量处理与可见进度；这里展示制作思路，不伪造一轮转换结果。'],['做成可以带走的工具。','已有 macOS 和 Windows 桌面版本。具体资产与版本请从下载页查看。']];app.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{app.querySelectorAll('[data-step]').forEach(x=>x.setAttribute('aria-pressed',x===b));document.querySelector('#step-title').textContent=steps[b.dataset.step][0];document.querySelector('#step-copy').textContent=steps[b.dataset.step][1]});window.scrollTo(0,0)}
document.querySelector('dialog>button').onclick=()=>document.querySelector('dialog').close();addEventListener('hashchange',render);render();
