const $=s=>document.querySelector(s),categories={visual:'视觉',writing:'写作',knowledge:'研究',building:'构建',personal:'个人'};let category='visual',savedScroll=0,coffeeTimer;const reduce=matchMedia('(prefers-reduced-motion: reduce)');
function url(state){history.replaceState(null,'','#'+state)}
function openBook(){ $('#cover').hidden=true;$('#book').hidden=false;url('skills-'+category);$('#category-title').focus({preventScroll:true});}
function list(cat){category=categories[cat]?cat:'visual';$('#category-title').textContent=categories[category]+' / 方法索引';const items=publicSkills.filter(s=>s.category===category);$('#category-count').textContent=items.length+' 个公开条目';$('#skill-list').replaceChildren();for(const s of items){if(s.id==='loki-social'){const b=document.createElement('button');b.className='card-entry';b.id='social-entry';b.innerHTML='<span><b>Loki 社交卡片</b><small>真实输出 / 抽出方法卡</small></span><span>↗</span>';b.onclick=()=>showCard();$('#skill-list').append(b)}else{const d=document.createElement('details');d.className='skill-row';const summary=document.createElement('summary');summary.textContent=s.title+' ＋';const p=document.createElement('p');p.textContent=s.summary;const note=document.createElement('small');note.textContent='本试刊仅展示已公开介绍；图像插页尚未制作。';d.append(summary,p,note);$('#skill-list').append(d)}}$('#tabs').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.cat===category)));$('#breadcrumb').textContent='目录 / 制作手册 / '+categories[category];}
for(const [id,label]of Object.entries(categories)){const b=document.createElement('button');b.textContent=label;b.dataset.cat=id;b.onclick=()=>{if(!$('#insert').hidden)hideCard(false);list(id);url('skills-'+id)};$('#tabs').append(b)}
function showCard(){savedScroll=scrollY;$('#catalogue').hidden=true;$('#insert').hidden=false;$('#breadcrumb').textContent='制作手册 / 视觉 / 社交卡片';url('card-loki-social');$('#insert-title').focus({preventScroll:true});$('#right-page');$('#return-card').scrollIntoView({block:'nearest',behavior:'instant'});}
function hideCard(focus=true){$('#insert').hidden=true;$('#catalogue').hidden=false;$('#breadcrumb').textContent='目录 / 制作手册 / '+categories[category];url('skills-'+category);if(focus){$('#social-entry')?.focus({preventScroll:true});scrollTo({top:savedScroll,behavior:'instant'})}}
function chapter(daily){$('#skills-page').hidden=daily;$('#break-page').hidden=!daily;$('#skills-chapter').setAttribute('aria-pressed',String(!daily));$('#daily-chapter').setAttribute('aria-pressed',String(daily));$('#page-number').textContent=daily?'02 / 中场休息':'01 / 制作手册';$('#breadcrumb').textContent=daily?'目录 / 中场休息':'目录 / 制作手册 / '+categories[category];url(daily?'break':'skills-'+category);if(daily)$('#break-page h2').focus({preventScroll:true});else{if(!$('#insert').hidden)hideCard(false);$('#category-title').focus({preventScroll:true})}}
$('#open-book').onclick=openBook;$('#close-book').onclick=()=>{$('#book').hidden=true;$('#cover').hidden=false;url('cover');$('#open-book').focus({preventScroll:true});scrollTo({top:0,behavior:'instant'})};$('#return-card').onclick=()=>hideCard();$('#skills-chapter').onclick=()=>chapter(false);$('#daily-chapter').onclick=()=>chapter(true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#insert').hidden)hideCard()});
const cup=$('#cup-button');cup.onclick=()=>{if(cup.disabled)return;cup.disabled=true;cup.classList.add('filling');cup.setAttribute('aria-busy','true');$('#cup-label').textContent='正在续杯…';$('#coffee-status').textContent='咖啡入杯，冰块浮起来了。';cup.querySelector('svg').setAttribute('aria-label','正在注入咖啡的杯子');coffeeTimer=setTimeout(()=>{cup.classList.replace('filling','full');cup.removeAttribute('aria-busy');cup.querySelector('svg').setAttribute('aria-label','装满冰美式的杯子');$('#cup-label').textContent='满杯，慢慢喝 ✓';$('#coffee-status').textContent='续杯好了。歇一会儿，再继续做。';$('#empty-cup').hidden=false},reduce.matches?0:1550)};
$('#empty-cup').onclick=()=>{clearTimeout(coffeeTimer);cup.classList.remove('full','filling');cup.disabled=false;cup.removeAttribute('aria-busy');cup.querySelector('svg').setAttribute('aria-label','空的冰美式杯');$('#cup-label').textContent='点杯子，续一杯 ↗';$('#coffee-status').textContent='杯子空了，冰块还在。';$('#empty-cup').hidden=true;cup.focus({preventScroll:true})};
const initial=location.hash.slice(1);list(initial.startsWith('skills-')?initial.slice(7):'visual');if(initial&&initial!=='cover'){openBook();if(initial==='card-loki-social')showCard();if(initial==='break')chapter(true)}
