/* Curated real local outputs. Public-facing fields are intentionally separated from source manifests. */
(()=>{const c=window.lokiCorpus;if(!c)return;const reading=!!document.querySelector('#app'),pre=(reading||location.pathname.includes('/projects/'))?'../':'',e=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function headline(k,title,copy){return `<div class="corpus-heading"><span>${k}</span><h3>${title}</h3><p>${copy}</p></div>`}
function methodText(text){const lines=text.split('\n').filter(x=>x.trim());const lead=lines.shift()||'';return `<p>${e(lead.replace(/^- /,''))}</p>${lines.length?`<details class="method-source"><summary>展开适用场景与完整证据</summary>${lines.map(line=>`<p>${e(line.replace(/^- /,''))}</p>`).join('')}</details>`:''}`}
function draw(){const id=document.querySelector('[data-reading-archive]')?'daily-insight':location.hash.split('/')[2],panel=document.querySelector('.directory-insert'),isReading=id==='book'||id==='daily-insight';if(!panel||panel.querySelector('.real-corpus'))return;let html='';
if(id==='perspective-distillation')html=headline('PUBLIC PERSPECTIVES / 人物研究','不同的人，不同的判断方式。',`我已经给 ${c.personProjects} 个人建了档案，这里先放 ${c.people.length} 位。我想看清他们遇到事情时怎么想、怎么选，所以材料和测试都留着。下面这些是我整理的研究方法，别当成他们本人说过的话。`)+`<div class="people-programme" role="group" aria-label="选择人物研究">${c.people.map((p,i)=>`<button data-person="${i}" aria-pressed="${i===0}"><span>0${i+1}</span><b>${e(p.name)}</b><small>${e(p.label)}</small></button>`).join('')}</div><section class="person-research" aria-live="polite"></section>`;
if(isReading)html=headline('READING ARCHIVE / 已有拆书文稿','书读过，留下什么？',`这里放了 ${c.books.length} 篇拆书文稿。${e(c.reading.scope)}`)+`<div class="book-library"><div class="book-list" role="group" aria-label="选择拆书文稿">${c.books.map((b,i)=>`<button data-book="${i}" aria-pressed="${i===0}"><small>${'DAY '+String(b.day).padStart(2,'0')}</small><b>${e(b.title)}</b><span>↗</span></button>`).join('')}</div><article class="book-reading" aria-live="polite"></article></div><p class="corpus-boundary">拆书的方法我还没正式发到 GitHub，先把已经做出来的文稿放在这里。完整案例里也能按天切换阅读卡片，头四天的卡片样式保留着，后续文稿接在后面。</p>`;
if(id==='collage-poem')html=headline('DAILY COLLAGE / 保存下来的日子','一些话，变成了图。','从实际保存的拼贴诗成品里，挑出六张。霓虹、旧报纸、撕纸和波普，留住不同日子的语气。')+`<div class="real-collage-gallery">${c.collages.map((x,i)=>`<figure><button class="collage-open" data-collage="${i}" aria-label="放大：${e(x.title)}"><img src="${pre+x.image}" alt="${e(x.title)}，${e(x.style)}拼贴诗成品"><span>展开原图 ↗</span></button><figcaption><small>${x.date} / ${x.style}</small><b>${e(x.title)}</b></figcaption></figure>`).join('')}</div>`;
if(!html)return;
if(isReading){
 panel.querySelector('h2').textContent=c.reading.title;
 panel.querySelector('.detail-summary').textContent=c.reading.summary;
 panel.querySelectorAll(':scope > .detail-preview, :scope > .note, :scope > details, :scope > .out').forEach(x=>x.remove());
}
const section=document.createElement('section');section.className='real-corpus corpus-'+id;section.innerHTML=html;
const anchor=panel.querySelector('.detail-summary');if(anchor)anchor.after(section);else panel.prepend(section);
if(isReading||id==='collage-poem')panel.querySelector('.making-notes')?.remove();
if(isReading||id==='collage-poem')panel.querySelectorAll('.no-sample').forEach(x=>x.remove());
if(id==='perspective-distillation'){
const show=i=>{const p=c.people[i];section.querySelectorAll('[data-person]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.person)===i));section.querySelector('.person-research').innerHTML=`<div class="person-heading"><span>研究摘录 / ${e(p.label)}</span><h4>${e(p.name)}</h4><small>${e(p.version)}</small></div><p class="person-progress">${e(p.progress)}</p><div class="person-methods">${p.methods.map((m,n)=>`<article><small>0${n+1} / 判断动作</small><h5>${e(m.title)}</h5>${methodText(m.text)}</article>`).join('')}</div><p class="corpus-boundary">这些分数来自项目内部出的题，各人的题量和评分规则都不同，不能排成谁更像本人的榜单。我把原文摘录放在这里，方便你看它到底从哪些材料里来。</p>`};section.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>show(Number(b.dataset.person)));show(0)}
if(isReading){const show=i=>{const b=c.books[i];try{sessionStorage.setItem('loki-reading-book',b.title)}catch{};section.querySelectorAll('[data-book]').forEach(x=>x.setAttribute('aria-pressed',Number(x.dataset.book)===i));section.querySelector('.book-reading').innerHTML=`<span class="book-date">DAY ${String(b.day).padStart(2,'0')} / ${b.date}</span><h4>《${e(b.title)}》</h4><div class="book-insight"><small>文稿里留下的核心洞见</small><p>${e(b.insight)}</p></div>${b.excerpt?`<details class="book-excerpt"><summary>读一段当天保存的原文</summary><small>Cola 生成的导读原文节选，保留当时表述，未逐页核对原书</small>${b.excerpt.split(/\n\s*\n/).filter(x=>x.trim()!=='---').map(x=>`<p>${e(x.replace(/\*\*/g,'').replace(/`/g,''))}</p>`).join('')}</details>`:''}<h5>这篇怎么展开</h5><ol>${b.contents.map(x=>`<li>${e(x)}</li>`).join('')}</ol><p class="corpus-boundary">${e(b.level)}</p>`;document.dispatchEvent(new CustomEvent('loki:reading-selected',{detail:{day:b.day}}))};section.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>show(Number(b.dataset.book)));let saved;try{saved=sessionStorage.getItem('loki-reading-book')}catch{};show(Math.max(0,c.books.findIndex(b=>b.title===(saved==='百年孤独'?'活着为了讲述':saved==='心流：最优体验心理学'?'心流':saved))))}
section.querySelectorAll('[data-collage]').forEach(b=>b.onclick=()=>{const x=c.collages[Number(b.dataset.collage)],modal=document.querySelector('#lightbox');modal.querySelector('img').src=pre+x.image;modal.querySelector('img').alt=x.title+' · '+x.date;modal.showModal()});
}
addEventListener('hashchange',draw);draw();})();
