(()=>{
const cup=document.querySelector('#cup-button'),status=document.querySelector('#coffee-status'),label=document.querySelector('#cup-label'),reset=document.querySelector('#empty-cup');
const drinks={coffee:{name:'冰美式',title:'冰美式续命。',intro:'忙的时候，来一杯。',empty:'杯子空了，七块冰还在。',action:'点杯子，续一杯 ↗',busy:'咖啡入杯，冰块浮起来了。',done:'满杯，慢慢喝。歇一会儿，再继续做。',duration:1550},green:{name:'绿茶',title:'喝茶，慢一点。',intro:'冰美式续命，品茶是爱好。',empty:'一杯清水，等茶色慢慢展开。',action:'点杯子，泡绿茶 ↗',busy:'茶色慢慢浸开，先歇一会儿。',done:'绿茶泡好了。这一页，可以慢慢看。',color:'#a5bc50',surface:'#d4e4a0',duration:2050},oolong:{name:'乌龙茶',title:'这一杯，留给乌龙。',intro:'换一种节奏，先不聊工作。',empty:'一杯清水，等茶色慢慢展开。',action:'点杯子，泡乌龙 ↗',busy:'清水染上琥珀色，慢慢来。',done:'乌龙泡好了。慢慢品，不急着翻页。',color:'#b98638',surface:'#e9c485',duration:2050}};
let selected='coffee',timer;
function prepare(){clearTimeout(timer);cup.classList.remove('filling','full','tea');cup.disabled=false;cup.removeAttribute('aria-busy');const d=drinks[selected];if(selected!=='coffee'){cup.classList.add('tea');cup.style.setProperty('--tea-color',d.color);cup.style.setProperty('--tea-surface',d.surface)}document.querySelector('#drink-title').textContent=d.title;document.querySelector('#drink-intro').textContent=d.intro;status.textContent=d.empty;label.textContent=d.action;cup.setAttribute('aria-label',d.action);cup.querySelector('svg').setAttribute('aria-label',selected==='coffee'?'装有七块冰的空咖啡杯':'盛有清水的茶杯');reset.hidden=true;document.querySelectorAll('[data-drink]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.drink===selected)))}
cup.onclick=()=>{if(cup.disabled)return;const d=drinks[selected];cup.disabled=true;cup.setAttribute('aria-busy','true');cup.classList.add('filling');label.textContent=selected==='coffee'?'正在续杯…':'茶色慢慢展开…';status.textContent=d.busy;cup.querySelector('svg').setAttribute('aria-label',d.busy);timer=setTimeout(()=>{cup.classList.replace('filling','full');cup.removeAttribute('aria-busy');label.textContent=d.name+'好了 ✓';status.textContent=d.done;cup.querySelector('svg').setAttribute('aria-label',d.name+'已准备好');reset.textContent=selected==='coffee'?'再看一次续杯过程 ↻':'再泡一次 ↻';reset.hidden=false},matchMedia('(prefers-reduced-motion: reduce)').matches?0:d.duration)};
reset.onclick=()=>{prepare();cup.focus({preventScroll:true})};document.querySelectorAll('[data-drink]').forEach(b=>b.onclick=()=>{selected=b.dataset.drink;prepare()});prepare();
const bookmark=document.querySelector('#bookmark');let marked='';bookmark.onclick=()=>{if(marked){marked='';bookmark.setAttribute('aria-pressed','false');document.querySelector('#bookmark-status').textContent='书签收好了。';bookmark.setAttribute('aria-label','标记正在看的位置')}else{marked=document.querySelector('#breadcrumb').textContent;bookmark.setAttribute('aria-pressed','true');document.querySelector('#bookmark-status').textContent='记在这里：'+marked;bookmark.setAttribute('aria-label','移除书签：'+marked)}};
})();
