(() => {
const $=s=>document.querySelector(s), d=window.bookData;
const names={visual:'视觉',writing:'写作',knowledge:'研究',building:'构建',personal:'个人'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(href,label)=>`<a class="source" href="${esc(href)}" target="_blank" rel="noopener">${esc(label)} <span>外部链接 ↗</span></a>`;
const routeLink=(r,t,cls='')=>`<a class="${cls}" href="#${r}">${t}</a>`;
const egg=(id,label,title,body)=>`<span class="aside-egg"><button popovertarget="${id}" class="egg">${label}</button><aside id="${id}" popover class="pocket"><button class="pocket-close" popovertarget="${id}" popovertargetaction="hide" aria-label="收好小纸条">×</button><small>夹在场刊里的一点私心</small><h3>${title}</h3>${body}</aside></span>`;
const photo=(src,caption)=>`<figure><button class="photo" data-photo="${esc(src)}" data-caption="${esc(caption)}" aria-label="放大查看：${esc(caption)}"><img src="${esc(src)}" alt="${esc(caption)}"><span>展开看大图 ⤢</span></button><figcaption>${esc(caption)}</figcaption></figure>`;
const stageEgg=()=>egg('sisters','票根 / 浪姐 ＋','三季，三份偏爱。','<p><b>万茜</b><br>第一季</p><p><b>刘恋</b><br>第三季</p><p><b>陈昊宇</b><br>第五季</p><small>这是我的喜欢，不是观演记录。</small>');
$('#about-page').innerHTML=`<span class="label">01 / 认识 LOKI</span><div class="cast"><div><p class="handnote">台下看演出，散场继续做。</p><h2 tabindex="-1">我是 Loki。<br><em>喜欢现场，<br>也喜欢动手。</em></h2><p>AI 内容创作者、Vibe coder。写 Skill、做小工具，也把想法慢慢做成产品。</p><p>演唱会、Livehouse、话剧、舞剧、音乐剧——线下演出，是我生活里很重要的一部分。</p></div><figure class="cast-photo"><img src="assets/lettering/loki.jpg" alt="赛博小熊猫 Loki"><figcaption>赛博小熊猫 / 本场主角</figcaption></figure></div><div class="personal-stamps"><span>AI 内容创作</span><span>Vibe coder</span><span>线下演出爱好者</span>${egg('supergirl','05 超女 ♫','这一枚，夹给 05 超女。','<p>喜欢 05 超女，也喜欢周笔畅、李宇春。</p><p>这些喜欢，不必都变成一个项目。留在小纸条上也很好。</p>')}</div><div class="next-spread"><span>接下来，把东西摊开给你看。</span>${routeLink('works','翻到作品节目单 →','source')}</div>`;
const favoriteEgg=egg('favorites','周也 / 角色收藏 ＋','周也，角色收藏夹。','<p>《锦月如歌》禾晏 · 《很想很想你》顾声</p><p>《护心》雁回 · 《别对我动心》岳千灵</p>');
$('#break-page').insertAdjacentHTML('beforeend',favoriteEgg);
$('.folio').insertAdjacentHTML('beforeend',egg('tea-note','茶签 ＋','续命和爱好，分开放。','<p>冰美式续命。绿茶、乌龙茶，慢慢品。</p><a class="source" href="#break">去泡一杯 →</a>'));
$('#book .book-bar>span:last-child').textContent='LOKI / 个人场刊';
$('.book-bottom>span:first-child').textContent='随时跳页，也欢迎多待一会儿。';
const dialog=document.createElement('dialog');dialog.id='image-view';dialog.innerHTML='<button id="close-image" aria-label="关闭大图">收回大图 ×</button><img alt=""><p></p>';document.body.append(dialog);
$('#close-image').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};
document.addEventListener('click',e=>{const b=e.target.closest('[data-photo]');if(b){dialog.querySelector('img').src=b.dataset.photo;dialog.querySelector('img').alt=b.dataset.caption;dialog.querySelector('p').textContent=b.dataset.caption;dialog.showModal()}});
let current='',category='visual';const positions=new Map();
function go(r){if(location.hash!=='#'+r)location.hash=r}
function showPage(id){for(const p of ['about','works','skills','break'])$('#'+p+'-page').hidden=p!==id;for(const p of ['about','works','skills','daily'])$('#'+p+'-chapter').setAttribute('aria-pressed',String(p===(id==='break'?'daily':id)));}
function works(id){showPage('works');const p=d.projects.find(p=>p.id===id);if(!p){$('#works-page').innerHTML=`<div class="page-heading"><span>02 / 七件公开作品</span><h2 tabindex="-1">这一场，做成了什么。</h2><p>选一张节目票，在场刊里展开看。</p></div><div class="program-tickets">${d.projects.map((p,i)=>routeLink('project-'+p.id,`<span class="ticket-no">${String(i+1).padStart(2,'0')}</span><span><b>${esc(p.title)}</b><small>${esc(p.tag)}</small></span><span class="ticket-arrow">展开 ↗</span>`,'program-ticket')).join('')}</div>${stageEgg()}`;return}
$('#works-page').innerHTML=`<a class="return" href="#works">↙ 收回跨页 · 作品节目单</a><div class="project-heading"><span class="label">02 / ${esc(p.tag)}</span><h2 tabindex="-1">${esc(p.title)}</h2><p>${esc(p.summary)}</p></div>${photo(p.image,p.imageAlt)}<p class="proof">${esc(p.proof)}</p>${p.systemEvidence?`<div class="method">${p.systemEvidence.map(e=>`<section><b>${esc(e.label)}</b><p>${esc(e.value)}</p></section>`).join('')}</div>`:''}<div class="status-slip"><b>${esc(p.status)}</b><p>${esc(p.verification.note)}</p><small>以上沿用项目记录 · ${esc(p.verification.checkedAt)}，不代表本次重新核验。</small></div>${p.publicLink?link(p.publicLink.href,p.publicLink.label):''}${d.skills.some(s=>s.href?.split('?')[0]===p.href)?`<div class="related-methods"><b>这件作品里的方法</b>${d.skills.filter(s=>s.href?.split('?')[0]===p.href).map(s=>routeLink('skill-'+s.id,esc(s.title)+' →')).join('')}</div>`:''}<nav class="leaf-nav">${routeLink('project-'+d.projects[(d.projects.indexOf(p)+1)%d.projects.length].id,'下一件作品 →')}</nav>`;
}
function skills(id){showPage('skills');const s=d.skills.find(s=>s.id===id);if(s)category=s.category;$('#tabs').innerHTML=Object.entries(names).map(([c,n])=>`<button data-cat="${c}" aria-pressed="${category===c}">${n}</button>`).join('');$('#tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>go('skills-'+b.dataset.cat));$('#catalogue').hidden=!!s;$('#insert').hidden=!s;
if(!s){$('#category-title').textContent=names[category]+' / 方法索引';const items=d.skills.filter(s=>s.category===category);$('#category-count').textContent=items.length+' 个条目 · 共 26 个公开方法';$('#skill-list').innerHTML=items.map((s,i)=>routeLink('skill-'+s.id,`<span class="method-number">${String(i+1).padStart(2,'0')}</span><span><b>${esc(s.title)}</b><small>${esc(s.tags.join(' / '))}</small></span><span>抽出 ↗</span>`,'method-card')).join('');return}
const profile=d.profiles[s.id], v=profile?.visual?.image?profile.visual:d.skillImages[s.id], flow=d.flows[s.id], gh=d.github[s.id]||{href:'https://github.com/loki2046-mao',label:'打开 Loki 的 GitHub',kind:'profile',note:'当前资料没有提供这个方法的独立公开源码链接；这里进入个人主页。'};
const project=d.projects.find(p=>p.href===s.href?.split('?')[0]);
$('#insert').innerHTML=`<a class="return" href="#skills-${category}">↙ 收回方法卡 · ${names[category]}目录</a><div class="insert-top"><span class="label">${names[category]} / ${esc(profile?.maturity||s.form)}</span><h2 id="insert-title" tabindex="-1">${esc(s.title)}</h2><p>${esc(s.summary)}</p></div>${v?photo(v.image,v.caption):''}<div class="cue-sheet"><small>工作路径 / 方法示意，不是运行截图</small><ol>${flow.map((f,i)=>`<li><span>${['输入','判断 / 处理','带走'][i]}</span><b>${esc(f)}</b></li>`).join('')}</ol></div>${profile?`<div class="method"><section><b>什么时候会用</b><p>${esc(profile.trigger)}</p></section><section><b>我会把关什么</b><p>${esc(profile.judgment)}</p></section></div><p class="result-note">${esc(profile.realResult)}</p><p class="boundary">${esc(profile.limitations)}</p>`:''}${!v?`<p class="boundary">${esc(profile?.evidenceStatus||'这一页先展示方法路径；对应的真实输出尚未收录，不用其他作品的图片代替。')}</p>`:''}${link(gh.href,gh.label)}<p class="boundary">${esc(gh.note)}</p>${project?routeLink('project-'+project.id,'翻到相关作品：'+esc(project.title)+' →','related-link'):s.id==='cyber-red-panda'?routeLink('about','认识 Loki →','related-link'):''}`;
}
function render(r){if(r==='skill-long-writing-memory'){history.replaceState(null,'','#project-inkpanda');r='project-inkpanda'}const old=current;if(old)positions.set(old,{y:scrollY,focus:document.activeElement?.getAttribute('href')});document.querySelectorAll(':popover-open').forEach(p=>p.hidePopover());current=r||'cover';$('#cover').hidden=current!=='cover';$('#book').hidden=current==='cover';if(current==='cover'){if(old)$('#open-book').focus({preventScroll:true});return}
let title='认识 Loki',page='01';if(current==='about'){showPage('about')}else if(current==='works'||current.startsWith('project-')){works(current.slice(8));title='作品节目单';page='02'}else if(current==='break'){showPage('break');title='中场休息';page='04'}else{if(current.startsWith('skills-')&&names[current.slice(7)])category=current.slice(7);const id=current.startsWith('skill-')?current.slice(6):current==='card-loki-social'?'loki-social':'';skills(id);title='制作手册 / '+names[category];page='03'}$('#breadcrumb').textContent='目录 / '+title;$('#page-number').textContent=page+' / '+title;
requestAnimationFrame(()=>{const saved=positions.get(current);const active=saved?.focus?[...document.querySelectorAll('a[href]')].find(a=>a.getAttribute('href')===saved.focus&&!a.closest('[hidden]')):null;(active||document.querySelector('.right-page section:not([hidden]) h2')||$('#insert-title'))?.focus({preventScroll:true});scrollTo({top:saved?.y||0,behavior:'instant'})});}
$('#open-book').onclick=()=>go('about');$('#close-book').onclick=()=>go('cover');$('#about-chapter').onclick=()=>go('about');$('#works-chapter').onclick=()=>go('works');$('#skills-chapter').onclick=()=>go('skills-'+category);$('#daily-chapter').onclick=()=>go('break');window.addEventListener('hashchange',()=>render(location.hash.slice(1)));render(location.hash.slice(1));
})();
