/* Preserve personal interactions across the old and new publication routes. */
(()=>{const lib=window.lokiPocketLegacy;if(!lib)return;const reading=!!document.querySelector('#app'),root=reading?'../':'',home=root+'index.html';
const labels={selfie:'◎ 小熊猫自拍',squash:'↗ 下班打壁球',concert:'♫ 演唱会打 call',tea:'♧ 随身茶签',supergirl:'05 超女 · 周笔畅 / 李宇春',sisters:'乘风 · 万茜 / 刘恋 / 陈昊宇',favorites:'周也 · 角色收藏'};
const modal=document.createElement('dialog');modal.className='personal-pocket-dialog';modal.setAttribute('aria-label','Loki 的随身口袋');modal.innerHTML='<button class="personal-pocket-close" aria-label="收起随身口袋">×</button><small>OFF THE CLOCK / 生活的另一面</small><h2>这些喜欢，也随身带着。</h2><div class="personal-pocket-content"></div>';document.body.append(modal);
const content=modal.querySelector('.personal-pocket-content');let previous;
function normalize(){content.querySelectorAll('[src^="assets/"]').forEach(x=>x.src=root+x.getAttribute('src'));content.querySelectorAll('a[href^="assets/"]').forEach(x=>x.href=root+x.getAttribute('href'));content.querySelectorAll('a[href="#break"]').forEach(x=>x.href=home+'#break')}
content.addEventListener('click',normalize);
function show(kind){modal.dataset.kind=kind;content.replaceChildren();modal.querySelectorAll('[data-pocket]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.pocket===kind));if(kind==='live-seat'){
const scenes=[['concert','演唱会','把荧光棒举高一点。','灯光越过看台，今晚跟着万人一起唱。'],['livehouse','Livehouse','离喜欢的声音，再近一点。','鼓点就在眼前，跟着节拍轻轻点头。'],['theatre','话剧','灯暗下来，故事开始了。','翻开节目册，把这段时间交给舞台上的人。'],['dance','舞剧','让身体替语言说话。','追着一道光，看动作和呼吸把故事慢慢展开。'],['musical','音乐剧','这一刻，忍不住想跟着唱。','等旋律落下，再把掌声送给谢幕的人。']];
content.innerHTML='<section class="seat-world" data-scene="concert"><div class="seat-world-header"><small>TONIGHT / 给生活留个座位</small><h3>今晚，想去<br>哪一种现场？</h3></div><div class="seat-choices" aria-label="选择现场氛围">'+scenes.map(([id,name],i)=>'<button data-scene-choice="'+id+'" aria-pressed="'+!i+'"><span>0'+(i+1)+'</span>'+name+'</button>').join('')+'</div><figure class="seat-scene"><img class="seat-scene-image" src="'+root+'assets/scenes/concert.png" alt="小熊猫在演唱会观众席举起荧光棒"><span class="seat-scene-tag">01 / CONCERT</span><figcaption><small>给自己留一晚</small><strong>把荧光棒举高一点。</strong></figcaption></figure><div class="seat-admission"><span class="seat-perforation" aria-hidden="true"></span><div><small>YOUR SEAT / 今晚的座位</small><p class="seat-ticket" aria-live="polite">演唱会 · 台下的我，准备好了。</p><p class="seat-description">灯光越过看台，今晚跟着万人一起唱。</p></div><b class="seat-number" aria-hidden="true">01</b></div></section>';
const world=content.querySelector('.seat-world'),art=content.querySelector('.seat-scene-image');
const english=['CONCERT','LIVEHOUSE','THEATRE','DANCE','MUSICAL'];
scenes.forEach(([id])=>{const preload=new Image();preload.src=root+'assets/scenes/'+id+'.png'});
content.querySelectorAll('.seat-choices button').forEach((b,i)=>b.onclick=()=>{const [id,name,title,desc]=scenes[i];world.dataset.scene=id;content.querySelectorAll('.seat-choices button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));art.src=root+'assets/scenes/'+id+'.png';art.alt='小熊猫作为观众，置身'+name+'的现场氛围';content.querySelector('.seat-scene-tag').textContent='0'+(i+1)+' / '+english[i];content.querySelector('.seat-scene figcaption strong').textContent=title;content.querySelector('.seat-ticket').textContent=name+' · 台下的我，准备好了。';content.querySelector('.seat-description').textContent=desc;content.querySelector('.seat-number').textContent='0'+(i+1)});

}else if(kind==='receipt'){
content.innerHTML='<section class="offstage-note receipt-note"><small>LOKI / 中场小票</small><h3>续的这一杯，<br>顺便带走一句话。</h3><p class="receipt-line" aria-live="polite">冰美式续命，茶慢慢品。</p><button class="receipt-next">再撕一张</button><small>NO DEADLINE ON THIS RECEIPT</small></section>';
const lines=['冰美式续命，茶慢慢品。','这一拍没接住，也可以再回一拍。','喜欢的东西，不必都变成作品。','散场以后，还有想做的事。'];let n=0;content.querySelector('.receipt-next').onclick=()=>content.querySelector('.receipt-line').textContent=lines[++n%lines.length];
}else if(kind==='encore'){
content.innerHTML='<section class="encore-desk"><div class="encore-underlay" aria-hidden="true"></div><div class="encore-paper"><span class="encore-tape" aria-hidden="true"></span><small class="encore-kicker">P.S. / 写在散场以后</small><h3>你居然<br>看到这里了<span>。</span></h3><div class="encore-message"><span class="encore-count">01 / 04</span><p class="encore-line" aria-live="polite">今天的工作先收起来。</p></div><span class="encore-sign">那就，再陪我待一会儿。<em>Loki</em></span><span class="encore-fold" aria-hidden="true"></span></div><img class="encore-panda" src="'+root+'assets/panda-audience-card-v2.png" alt="小熊猫抱着票根和冰美式，陪你等散场"><div class="encore-ticket"><span><small>ONE MORE THING</small><b>散场前的小声话</b></span><button class="encore-next">还有一句？ <span aria-hidden="true">↗</span></button></div><span class="encore-stamp" aria-hidden="true">灯还没全关<br>STAY A LITTLE</span></section>';
const lines=['耳机戴好，票根收好。','壁球拍也别落下。','下一场，继续做观众，也继续做东西。'];let n=0;content.querySelector('.encore-next').onclick=e=>{content.querySelector('.encore-line').textContent=lines[n++];content.querySelector('.encore-count').textContent=String(n+1).padStart(2,'0')+' / 04';const paper=content.querySelector('.encore-paper');paper.classList.remove('encore-turn');void paper.offsetWidth;paper.classList.add('encore-turn');if(n===lines.length){e.currentTarget.disabled=true;e.currentTarget.textContent='下次见。';content.querySelector('.encore-sign').innerHTML='这次真的散场啦。<em>Loki</em>';content.querySelector('.encore-ticket').classList.add('encore-finished')}};
}else if(kind==='selfie'){
content.innerHTML='<section class="panda-photobooth"><div class="selfie-print" data-frame="cream"><small>LOKI / ONE MORE SHOT</small><div class="selfie-window"><div class="selfie-pose" role="img" aria-label="椰子面对镜头"></div><span class="print-star" aria-hidden="true">✳</span></div><p class="selfie-caption" aria-live="polite">今天也留一张。</p><span class="print-number">NO. 001 / KEEP THIS MOMENT</span></div><div class="selfie-frames" aria-label="选择拍立得相框"></div><div class="selfie-actions"><button class="selfie-change">换个姿势 ↻</button><button class="selfie-shutter">咔嚓，拍一张 ◎</button><button class="selfie-keep" disabled>夹进相册 ＋</button></div><p class="selfie-status" role="status">小熊猫摆拍照相馆</p><div class="selfie-album"></div></section>';
const poses=[[0,0,'正面营业'],[0,3,'挥手打招呼'],[2,4,'跳起来了'],[3,9,'看向另一边']];let pose=0,taken=false,frame='cream';
const frames={cream:'奶油白',mint:'薄荷格纹',ticket:'粉色票根',film:'黑色胶片'};
const print=content.querySelector('.selfie-print'),framePicker=content.querySelector('.selfie-frames');
for(const [key,name] of Object.entries(frames)){const b=document.createElement('button');b.type='button';b.dataset.frame=key;b.setAttribute('aria-pressed',String(key===frame));b.innerHTML='<i aria-hidden="true"></i>'+name;b.onclick=()=>{frame=key;print.dataset.frame=key;framePicker.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));status.textContent=taken?'相框换好了，可以夹进相册。':'相框选好了，给椰子拍一张。'};framePicker.append(b)}
const art=content.querySelector('.selfie-pose'),caption=content.querySelector('.selfie-caption'),status=content.querySelector('.selfie-status');art.style.backgroundImage='url('+root+'assets/process/coconut.webp)';
const render=()=>{const [x,y,label]=poses[pose];art.style.backgroundPosition=(-x*192)+'px '+(-y*208)+'px';art.setAttribute('aria-label','椰子 · '+label);caption.textContent=label};render();
content.querySelector('.selfie-change').onclick=()=>{pose=(pose+1)%poses.length;render();taken=false;content.querySelector('.selfie-keep').disabled=true;status.textContent='姿势换好了，再拍一张。'};
content.querySelector('.selfie-shutter').onclick=()=>{taken=true;content.querySelector('.selfie-print').classList.remove('selfie-taken');void art.offsetWidth;content.querySelector('.selfie-print').classList.add('selfie-taken');caption.textContent='散场以后，记得开心。';status.textContent='拍好了，这张可以夹进相册。';content.querySelector('.selfie-keep').disabled=false};
function album(){let saved;try{saved=JSON.parse(localStorage.getItem('loki-selfie')||'null')}catch{};if(saved&&Number.isInteger(saved.pose)&&poses[saved.pose]){const [x,y,label]=poses[saved.pose];content.querySelector('.selfie-album').innerHTML='<small>相册里留着的这一张</small><div class="selfie-print" data-frame="'+(frames[saved.frame]?saved.frame:'cream')+'"><small>LOKI / LITTLE MOMENTS</small><div class="selfie-window"><div class="selfie-pose" role="img" aria-label="收藏的椰子自拍：'+label+'" style="background-image:url('+root+'assets/process/coconut.webp);background-position:'+(-x*192)+'px '+(-y*208)+'px"></div><span class="print-star" aria-hidden="true">✳</span></div><p class="selfie-caption">'+label+'</p><span class="print-number">'+(frames[saved.frame]||frames.cream)+' / LOKI</span></div>'}}
content.querySelector('.selfie-keep').onclick=()=>{if(!taken)return;try{localStorage.setItem('loki-selfie',JSON.stringify({pose,frame}));album();status.textContent='已夹进相册，下次打开还在。'}catch{status.textContent='当前浏览器无法保存，这张还留在眼前。'}};album();
}else if(['supergirl','sisters','favorites'].includes(kind)){
// Temporarily use the legacy renderer's lookup ID without duplicating IDs on the home page.
const existing=document.getElementById(kind);if(existing)existing.id=kind+'-home-retained';const node=document.createElement('section');node.id=kind;content.append(node);lib.pocket(kind);node.removeAttribute('id');if(existing)existing.id=kind;
}else{const node=lib.stamp(kind);content.append(node);node.querySelector('.wristband').remove();node.querySelector('.wristband-reveal').hidden=false;if(kind==='concert'){node.querySelector('.concert-mini').outerHTML='<button class="panda-ticket" aria-label="让小熊猫举起票根"><img src="'+root+'assets/panda-audience-card-v2.png" alt="小熊猫举票插画"><span>点一下，举起偏爱 ↗</span></button>';node.querySelector('.panda-ticket').onclick=()=>{lib.celebrate(node.querySelector('.panda-ticket'));node.querySelector('.panda-ticket span').textContent='这一枚，留给现场。'}}}normalize()}
function open(kind){previous=document.activeElement;show(kind);if(!modal.open)modal.showModal();modal.querySelector('.personal-pocket-close').focus()}
modal.querySelector('.personal-pocket-close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});modal.addEventListener('close',()=>previous?.isConnected&&previous.focus());
// Small, sparse physical clues. No global launcher or catalogue of surprises.
function clue(parent,kind,mark,label){if(!parent||parent.querySelector('[data-secret="'+kind+'"]'))return;const b=document.createElement('button');b.className='quiet-clue';b.dataset.secret=kind;b.textContent=mark;b.setAttribute('aria-label',label);b.onclick=()=>open(kind);parent.append(b)}
function plant(){const panel=document.querySelector('.directory-insert'),id=location.hash.split('/')[2];
const clues={
'ebook-workflow':['squash','↗ 01','翻开球拍挂签'],
'loki-writing':['tea','一叶','翻开夹在稿纸里的茶签'],
'film-poster':['favorites','角色书签','翻开角色书签'],
'notes':['supergirl','05','翻开旧票根'],
'lian-curation':['sisters','01 / 03 / 05','翻开三季票夹'],
'inkpanda':['concert','ADMIT ONE','翻开观众票根'],
'image-kit':['selfie','◎','打开小熊猫照相馆']};
if(panel&&clues[id]){const [kind,mark,label]=clues[id];clue(panel.querySelector('.item-navigation'),kind,mark,label)}
const portrait=document.querySelector('#cover .cover-character');if(portrait&&!portrait.querySelector('.portrait-secret')){const img=portrait.querySelector('img');if(img){const b=document.createElement('button');b.className='portrait-secret';b.setAttribute('aria-label','轻点小熊猫，留张照片');b.onclick=()=>open('selfie');img.before(b);b.append(img)}}
clue(document.querySelector('#about-page .cast-photo'),'live-seat','座位 01','翻开现场座位签');
clue(document.querySelector('#break-page'),'receipt','— THANK YOU —','翻开杯子旁的小票');
if(!reading)clue(document.querySelector('.publication-footer')||document.querySelector('.cover-bottom'),'encore','…','读到散场字幕之后');
}
if(window.lokiRoutes)window.lokiRoutes.register('pockets',plant);else{addEventListener('hashchange',plant);plant();}})();
