/* First-person editorial accounts drawn from the local source manifest. */
(()=>{const data=window.lokiProcess;if(!data)return;const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function draw(){const id=location.hash.split('/')[2],record=data[id],panel=document.querySelector('.directory-insert');if(!record||!panel||panel.querySelector('.process-archive'))return;
const section=document.createElement('section');section.className='process-archive';section.dataset.case=id;
section.innerHTML=`<div class="archive-binding"><span>LOKI / BACKSTAGE FILES</span><span>制作档案 ↙</span></div><header><p class="archive-stamp">OPEN THE PROCESS</p><h3>${e(record.title)}</h3><p>${e(record.intro)}</p></header>${record.pet?`<section class="pet-rehearsal"><div class="pet-stage"><button class="coconut-sprite" aria-label="和椰子打个招呼"></button><p class="pet-speech" aria-live="polite">椰子已到场。选个动作，看看它怎么动。</p></div><div class="pet-controls" role="group" aria-label="选择椰子的动作"><button data-pet="idle" aria-pressed="true">待机</button><button data-pet="right" aria-pressed="false">向右跑</button><button data-pet="left" aria-pressed="false">向左跑</button><button data-pet="wave" aria-pressed="false">打招呼</button><button data-pet="jump" aria-pressed="false">跳一下</button><button data-pet="pause" aria-pressed="false">暂停</button></div><small>COCONUT / 原始宠物图集 · 动作排练</small></section>`:''}${record.gallery?`<div class="archive-proofwall">${record.gallery.map(([src,caption])=>`<figure><button class="archive-enlarge" data-src="../${e(src)}" aria-label="放大：${e(caption)}"><img loading="lazy" decoding="async" src="../${e(src)}" alt="${e(caption)}"><span>展开保存原图 ↗</span></button><figcaption>${e(caption)}</figcaption></figure>`).join('')}</div>`:''}<ol class="archive-steps">${record.steps.map(([title,text],i)=>`<li><span class="archive-stepnum">0${i+1}</span><div><h4>${e(title)}</h4><p>${e(text)}</p></div></li>`).join('')}</ol>${record.variants?`<section class="title-trials"><h4>翻一张标题试印</h4><div role="group" aria-label="选择标题测试场景">${record.variants.map(([label],i)=>`<button data-trial="${i}" aria-pressed="${i===0}">${e(label)}</button>`).join('')}</div><article class="title-proof" aria-live="polite"></article></section>`:''}${record.secret?`<details class="archive-secret"><summary><span aria-hidden="true">✳</span> ${e(record.secret[0])} <span>＋</span></summary><p>${e(record.secret[1])}</p><small>FOUND IN THE MARGINS / 你翻到了页边</small></details>`:''}<details class="archive-source"><summary>这份档案从哪里来</summary><p>${e(record.sourceLabel)}</p><p>${e(record.note)}</p><small>依据保存材料整理的制作说明。</small></details>`;
panel.querySelector('.detail-summary').after(section);panel.querySelector('.making-notes')?.remove();panel.querySelector('.no-sample')?.remove();
if(record.gallery){const old=panel.querySelector('.detail-preview');if(old?.nextElementSibling?.classList.contains('note'))old.nextElementSibling.remove();old?.remove()}
panel.querySelector(':scope > details')?.remove();
section.querySelectorAll('.archive-enlarge').forEach(b=>b.onclick=()=>{const modal=document.querySelector('#lightbox');modal.querySelector('img').src=b.dataset.src;modal.querySelector('img').alt=b.querySelector('img').alt;modal.showModal()});
if(record.pet){const sprite=section.querySelector('.coconut-sprite'),poses={idle:[0,7],right:[1,8],left:[2,8],wave:[3,4],jump:[4,5]};sprite.dataset.pose='idle';const show=pose=>{section.querySelectorAll('[data-pet]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.pet===pose));if(pose==='pause'){sprite.style.animationPlayState='paused';return}const [row,frames]=poses[pose];sprite.style.setProperty('--pet-y',(-row*208)+'px');sprite.style.setProperty('--pet-end',(-frames*192)+'px');sprite.style.setProperty('--pet-frames',frames);sprite.style.animationPlayState='running';sprite.dataset.pose=pose};section.querySelectorAll('[data-pet]').forEach(b=>b.onclick=()=>show(b.dataset.pet));sprite.onclick=()=>{show('wave');section.querySelector('.pet-speech').textContent='抓到一只正在摸鱼的小熊猫。下一场，也一起去吧。'};show('idle')}
if(record.variants){const show=i=>{const [label,title,reason]=record.variants[i];section.querySelectorAll('[data-trial]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.trial)===i));section.querySelector('.title-proof').innerHTML=`<small>试印 0${i+1} / ${e(label)}</small><h5>${e(title)}</h5><p>${e(reason)}</p>`};section.querySelectorAll('[data-trial]').forEach(b=>b.onclick=()=>show(Number(b.dataset.trial)));show(0)}
}if(window.lokiRoutes)window.lokiRoutes.register('process',draw);else{addEventListener('hashchange',draw);draw();}})();
