window.LOKI_OS_SITE_DATA = Object.freeze({
  publicationStatus: 'verified',
  edition: 'seo-geo-local-review-v2',
  updatedAt: '2026-08-29',
  featuredProjectIds: Object.freeze(['interface-system', 'perspective-distillation', 'inkpanda']),
  pillars: Object.freeze([
    Object.freeze({ id: 'ai-writing', projectIds: Object.freeze(['inkpanda']), href: '#case-inkpanda', title: 'AI 写小说', summary: '我怎么让 AI 记住一部长篇' }),
    Object.freeze({ id: 'ai-products', projectIds: Object.freeze(['interface-system']), href: '#case-interface-system', title: '文科生用 AI 做项目', summary: '从想法、界面到真机上跑起来' }),
    Object.freeze({ id: 'ai-workflows', projectIds: Object.freeze(['daily-insight', 'loki-health']), href: '#workflow', title: 'AI 工作流 / 个人系统', summary: '我怎么把每天的事留下来' }),
  ]),
  proofStrip: Object.freeze([
    Object.freeze({ projectId: 'interface-system', href: './projects/interface-system.html', title: '界面系统', image: './projects/assets/real/cola/cola-9skins-v5-overview.png', imageAlt: 'Cola 九套真实运行时皮肤总览', caption: '从三种方向试起，后来做到九套', imageWidth: 1112, imageHeight: 1190, imageFit: 'contain' }),
    Object.freeze({ projectId: 'perspective-distillation', href: './projects/perspective-distillation.html', title: '人物视角蒸馏', image: './projects/assets/real/perspective/liuyang-stage.jpg', imageAlt: '人物视角蒸馏使用的刘旸公开节目材料样本', caption: '每个判断都要能回到公开来源', imageWidth: 1080, imageHeight: 604, imageFit: 'cover' }),
    Object.freeze({ projectId: 'inkpanda', href: './projects/inkpanda.html', title: 'InkPanda', image: './projects/assets/real/inkpanda/outline.png', imageAlt: 'InkPanda 真实章节纲要界面', caption: '一部长篇被拆成小说、卷、章节和场景', imageWidth: 2000, imageHeight: 1114, imageFit: 'cover' }),
  ]),
  gearModules: Object.freeze([
    Object.freeze({ id: 'cola-skins', code: 'CASE-01', title: 'Cola 九套皮肤', readout: '我每天都要看它很久，就从三套代表方向试起，后来做到了九套，也让它记住上次的选择。', proof: '九套原型与真机运行画面', href: './projects/interface-system.html?room=cola', action: '看真实界面', image: './projects/assets/real/cola/inject-shot-1.png', tags: Object.freeze(['9 套原型', '真机运行', '选择记忆']) }),
    Object.freeze({ id: 'hub-skins', code: 'CASE-02', title: 'Loki Hub 十二套界面', readout: '同一批真实内容换了十二种界面。我逐套检查桌面阅读、手机顺序和切换动作。', proof: '十二套真实界面与桌面、移动端验收', href: './projects/interface-system.html?room=hub', action: '看真实页面', image: './projects/assets/real/hub/ui-selection-board.png', tags: Object.freeze(['12 套界面', '真实内容', '双端验收']) }),
    Object.freeze({ id: 'codex-theme', code: 'CASE-03', title: 'Codex 刘恋拼贴主题', readout: '背景图很快就能换。菜单、弹窗、任务卡、输入区和透明宠物，才是后来真正费工夫的地方。', proof: '四类核心组件与真实人物资产', href: './projects/interface-system.html?room=codex', action: '看完整改造', image: './projects/assets/exhibition/codex-liulian-cutout.webp', tags: Object.freeze(['任务卡', '对话框', '宠物分离']) }),
    Object.freeze({ id: 'daily-insight', code: 'CASE-04', title: '每日洞见 · unbook', readout: '我想坚持读两年书，又怕读完就忘，于是每天只留一个冲突、一个边界和一个问题。', proof: '四天真实洞见、四套工具与四个问题', href: './projects/daily-insight.html', action: '翻开四天记录', image: './projects/assets/exhibition/hub-real-verify-ui-body.webp', tags: Object.freeze(['Day 01—04', '洞见卡', '复习入口']) }),
    Object.freeze({ id: 'perspective', code: 'CASE-05', title: '人物视角蒸馏', readout: '我把公开材料拆开，看四个人遇到问题时先看什么、会怎么改，也把不知道的地方留着。', proof: '四个人物、公开证据与隔离留出评测', href: './projects/perspective-distillation.html', action: '进入四人工作区', image: './projects/assets/real/perspective/liulian-evidence-sheet-01.png', tags: Object.freeze(['刘恋', '刘旸', '鲁豫', 'Papi酱']) }),
    Object.freeze({ id: 'ebook', code: 'CASE-06', title: 'Loki 电子书转换器', readout: '把 Calibre 的复杂转换能力，做成不需要命令行的拖拽桌面工具。', proof: 'macOS 与 Windows 真实安装包', href: './projects/ebook-converter.html', action: '看产品怎么把复杂度藏起来', image: './projects/assets/real/ebook/app-home.png', tags: Object.freeze(['macOS 1.1.2', 'Windows 1.1.1', '批量转换']) }),
    Object.freeze({ id: 'inkpanda', code: 'CASE-07', title: 'InkPanda 长篇写作', readout: '写到第八十章，人物受过的伤和前面埋的伏笔很容易丢。我做了一个能替作者照看这些事的工作台。', proof: '首页、编辑器、纲要与发现页真实界面', href: './projects/inkpanda.html', action: '看真实产品与长篇判断', image: './projects/assets/real/inkpanda/editor.png', tags: Object.freeze(['长篇结构', '上下文记忆', '一致性检查']) }),
    Object.freeze({ id: 'lian', code: 'CASE-08', title: '恋之上上签', readout: '我从 44 首歌里手工挑了 147 条短句，还先给自己定下版权边界，再做抽签和卡片。', proof: '44 首歌、147 条精选短句与 16 套卡片视觉', href: './projects/lian.html', action: '看喜欢怎样变成作品', image: './projects/assets/real/lian/draw-result.jpg', tags: Object.freeze(['44 首歌', '147 条短句', '16 套视觉']) }),
  ]),
  projects: [
    {
      id: 'interface-system', date: '08-24', title: '个人化界面系统',
      summary: '我每天都要面对这些 AI 工具。前段时间从换颜色开始，后来一路改到菜单、弹窗、输入区和更新后的恢复。',
      tag: 'COLA × HUB × CODEX', href: './projects/interface-system.html',
      action: '看我怎么把它改到真机上', linkStatus: 'internal', visibility: 'public', group: 'flagship', order: 1,
      accent: '#ff6508', eyebrow: 'COLA × LOKI HUB × CODEX / 通用工具如何变成个人空间', anchor: 'case-interface-system',
      image: './projects/assets/real/cola/inject-shot-1.png',
      imageAlt: 'Cola 个性化界面真机运行截图',
      imageWidth: 2560, imageHeight: 1600, imageFit: 'cover',
      proof: '九套皮肤进入真实工具并记住选择。',
      status: '公开案例 · 真机界面已验证',
      verification: Object.freeze({ status: 'verified', checkedAt: '2026-08-28', scope: 'local-browser', note: '真机界面与本地案例页已核验' }),
    },
    {
      id: 'loki-ebook-converter', date: '08-11', title: 'Loki 电子书转换器',
      summary: '把 Calibre 强大但复杂的转换能力做成普通人可拖拽、批量处理、看见进度的桌面工具。',
      tag: 'MACOS 1.1.2 · WIN 1.1.1',
      href: './projects/ebook-converter.html',
      action: '看我如何把复杂能力做简单', linkStatus: 'internal', visibility: 'public', group: 'productization', order: 6,
      accent: '#ff397f', eyebrow: 'MACOS 1.1.2 × WINDOWS 1.1.1 / 把 Calibre 藏进拖拽入口',
      image: './projects/assets/real/ebook/app-home.png',
      imageAlt: 'Loki 电子书转换器真实桌面界面',
      imageWidth: 1280, imageHeight: 900, imageFit: 'cover',
      proof: '真实桌面应用界面；Release v1.1.2 页面与 universal DMG 资产记录已复核。',
      status: '已发布产品 · Release 已复核',
      publicLink: Object.freeze({ href: 'https://github.com/loki2046-mao/loki-ebook-converter/releases/tag/v1.1.2', label: 'Release v1.1.2（已复核）', status: 'verified', checkedAt: '2026-08-29' }),
      verification: Object.freeze({ status: 'verified', checkedAt: '2026-08-29', scope: 'release-page', note: '站内案例、Release 页面与 universal DMG 资产记录已复核；本轮未下载或安装 DMG' }),
    },
    {
      id: 'daily-insight', date: '08-25', title: '730 天每日洞见系统',
      summary: '我读完书常常记不住当时为什么被击中，于是每天留下一次冲突、一个边界和一个以后还想回答的问题。',
      tag: '阅读系统', href: './projects/daily-insight.html',
      action: '看我如何让长期目标运行', linkStatus: 'internal', visibility: 'public', group: 'workflow', order: 4,
      accent: '#eee5d5', eyebrow: '阅读 × 回看 × 长期记忆 / 每天留下一张未来会回来找我的卡',
      image: './projects/assets/exhibition/reading-desk-v1.webp',
      imageAlt: '每日洞见系统公开展台的视觉导览图',
      imageWidth: 1915, imageHeight: 821, imageFit: 'cover',
      proof: '视觉导览：730 天阅读系统的公开展台；四天洞见样例请进入案例页查看。',
      status: '公开案例 · 真实样例持续补充',
      systemKind: 'AI 阅读工作流',
      systemEvidence: Object.freeze([
        Object.freeze({ label: '每日动作', value: '从一本书留下一个冲突、边界和问题' }),
        Object.freeze({ label: '留下记录', value: '公开案例页已有四天洞见卡结构' }),
        Object.freeze({ label: '未来调用', value: '按日期回看，生成完以后还会再回来' }),
      ]),
      verification: Object.freeze({ status: 'pending', checkedAt: '2026-08-29', scope: 'local-browser', note: '案例页结构已核验，长期连续运行证据仍在补充' }),
    },
    {
      id: 'perspective-distillation', date: '08-25', title: '人物视角蒸馏',
      summary: '我喜欢看一个人遇到麻烦时先看什么、最后留下什么。公开材料被拆成证据，再拿没见过的新题检查判断会不会走样。',
      tag: 'NUWA 改造', href: './projects/perspective-distillation.html',
      action: '看我如何蒸馏隐性判断', linkStatus: 'internal', visibility: 'public', group: 'flagship', order: 2,
      accent: '#d7f43c', eyebrow: '公开证据 × 隔离评测 / 看判断动作能不能迁移',
      image: './projects/assets/real/perspective/liulian-evidence-sheet-01.png',
      imageAlt: '刘恋公开节目材料的时间帧采样',
      imageWidth: 1940, imageHeight: 1186, imageFit: 'contain',
      proof: '公开节目时间帧采样；完整来源、四人档案与隔离评测请进入案例页查看。',
      status: '研究型工作模型 · 内部评测',
      verification: Object.freeze({ status: 'verified', checkedAt: '2026-08-28', scope: 'local-browser', note: '公开材料证据表与内部评测页面已核验' }),
    },
    {
      id: 'loki-health', date: '08-22', title: "Loki's Health",
      summary: '围绕真实身体记录生长的本地优先健康 App；公开页只展示脱敏界面、产品判断与隐私边界。',
      tag: '我的身体节律', href: './projects/loki-health.html', action: '进入健康系统展台',
      linkStatus: 'internal', visibility: 'public', group: 'workflow', order: 5,
      accent: '#94d668', eyebrow: '本地优先 × 脱敏公开 / 让身体记录能够被照顾和回看',
      image: './projects/assets/real/health/today-desktop-redacted.png',
      imageAlt: "Loki's Health 本地真实产品的脱敏桌面截图",
      imageWidth: 1440, imageHeight: 1172, imageFit: 'contain',
      proof: '脱敏截图证明本地产品界面已形成；公开入口已复核可访问，具体交互仍待复核。',
      status: '本地真实系统 · 公开入口可访问，交互待复核',
      publicLink: Object.freeze({ href: 'https://lokihealthy.hiloki.ai/', label: '公开入口（已复核）', status: 'verified', checkedAt: '2026-08-29' }),
      systemKind: '个人记录系统（非 AI 核心）',
      systemEvidence: Object.freeze([
        Object.freeze({ label: '持续入口', value: '饮水、饮食、活动与身体目标集中记录' }),
        Object.freeze({ label: '留下记录', value: '只读同步与手动记录分开保存和回看' }),
        Object.freeze({ label: '公开边界', value: '仅展示脱敏截图，不公开真实健康数值' }),
      ]),
      verification: Object.freeze({ status: 'pending', checkedAt: '2026-08-29', scope: 'local-browser', note: '本地产品与脱敏素材已核验，公开入口 HTML 与核心资源已复核，具体交互待复核' }),
    },
    {
      id: 'inkpanda', date: '06-28', title: 'InkPanda · AI 长篇写作',
      summary: '写到后面，AI 会忘记人物受过的伤，也会漏掉早先的伏笔。作者继续写，系统负责把相关记忆找回来。',
      tag: '写作平台', href: './projects/inkpanda.html',
      action: '看真实产品与长篇判断', linkStatus: 'internal', visibility: 'public', group: 'flagship', order: 3,
      accent: '#d69a55', eyebrow: '上下文 × 记忆 × 一致性 / 让 AI 记住同一部长篇', anchor: 'case-inkpanda',
      image: './projects/assets/real/inkpanda/editor.png',
      imageAlt: 'InkPanda 真实编辑器界面',
      imageWidth: 2000, imageHeight: 1114, imageFit: 'cover',
      proof: '真实编辑器展示正文、上下文与写作工具；外部产品入口已复核可访问，登录后交互仍待复核。',
      status: '已发布产品 · 公开入口可访问，交互待复核',
      publicLink: Object.freeze({ href: 'https://inkxiaoxiongmao.hiloki.ai/', label: '产品入口（已复核）', status: 'verified', checkedAt: '2026-08-29' }),
      verification: Object.freeze({ status: 'pending', checkedAt: '2026-08-29', scope: 'local-browser', note: '站内案例与真实界面已核验，公开入口 HTML 与核心资源已复核，登录后交互待复核' }),
    },
    {
      id: 'lian', date: '06-17', title: '恋之上上签',
      summary: '把对刘恋的喜欢做成一件有版权边界、视觉判断和真实交互的歌词答案书。',
      tag: '歌词答案书', href: './projects/lian.html',
      action: '看喜欢如何变成作品', linkStatus: 'internal', visibility: 'public', group: 'personal-practice', order: 7,
      accent: '#ffb53e', eyebrow: '私人喜欢 × 产品边界 / 44 首歌与 147 条精选短句',
      image: './projects/assets/real/lian/draw-result.jpg',
      imageAlt: '恋之上上签真实抽签结果页',
      imageWidth: 2000, imageHeight: 1407, imageFit: 'cover',
      proof: '历史抽签结果截图与 16 套卡片视觉；外部入口已复核可访问，抽签交互仍待复核。',
      status: '公开作品 · 外部入口可访问，抽签交互待复核',
      publicLink: Object.freeze({ href: 'https://lian.hiloki.ai/', label: '作品入口（已复核）', status: 'verified', checkedAt: '2026-08-29' }),
      verification: Object.freeze({ status: 'pending', checkedAt: '2026-08-29', scope: 'local-browser', note: '站内案例与历史截图已核验，公开入口 HTML 与核心资源已复核，抽签交互待复核' }),
    },
  ],
});
