window.LOKI_OS_SITE_DATA = Object.freeze({
  updatedAt: '2026-08-25',
  projects: [
    {
      id: 'qichi-maintenance',
      date: '08-25',
      title: '栖迟系统 · 维护入口重建',
      summary: '真实源码、历史版本、改造记录与自动化重新收口。',
      tag: '系统维护',
      href: 'https://loki-os.hiloki.ai/',
      visibility: 'public',
    },
    {
      id: 'loki-ebook-converter',
      date: '08-11',
      title: 'Loki Ebook Converter',
      summary: '面向个人书库的电子书转换工具，持续工程化。',
      tag: '开源工具',
      href: 'https://github.com/loki2046-mao/loki-ebook-converter',
      visibility: 'public',
    },
    {
      id: 'cola-skills',
      date: '08-05',
      title: 'Cola Skills',
      summary: '把真实工作流沉淀成可复用、可安装的开源 Skills。',
      tag: '开源仓库',
      href: 'https://github.com/loki2046-mao/cola-skills',
      visibility: 'public',
    },
    {
      id: 'ai-career-compass',
      date: '07-05',
      title: 'AI Career Compass',
      summary: '围绕 AI 时代职业判断制作的开源项目。',
      tag: 'AI 产品',
      href: 'https://github.com/loki2046-mao/ai-career-compass',
      visibility: 'public',
    },
    {
      id: 'loki-life-progress',
      date: '07-01',
      title: 'Loki Life Progress',
      summary: '把长期目标和人生进度做成可见、可回看的系统。',
      tag: '人生系统',
      href: 'https://github.com/loki2046-mao/loki-life-progress',
      visibility: 'public',
    },
    {
      id: 'inkpanda',
      date: '06-28',
      title: 'InkPanda · 长篇写作平台',
      summary: '为长篇创作搭建的 AI 写作与工程化工作台。',
      tag: '写作平台',
      href: 'https://inkxiaoxiongmao.hiloki.ai',
      visibility: 'public',
    },
    {
      id: 'lian',
      date: '06-17',
      title: '恋之上上签',
      summary: '把歌词、情绪与抽签体验做成一间线上小屋。',
      tag: '互动作品',
      href: 'https://lian.hiloki.ai',
      visibility: 'public',
    },
    {
      id: 'content-station',
      date: '05-12',
      title: 'Content Station',
      summary: '个人内容生产与整理流程的开源实验。',
      tag: '内容系统',
      href: 'https://github.com/loki2046-mao/content-station',
      visibility: 'public',
    },
  ],
});
