window.LOKI_OS_SITE_DATA = Object.freeze({
  publicationStatus: 'verified',
  edition: 'seo-geo-local-review-v2',
  updatedAt: '2026-08-29',
  featuredProjectIds: Object.freeze(['interface-system', 'perspective-distillation', 'inkpanda']),
  pillars: Object.freeze([
    Object.freeze({ id: 'ai-writing', projectIds: Object.freeze(['inkpanda']), href: '#case-inkpanda', title: 'AI 写小说', summary: '我怎么让 AI 记住一部长篇' }),
    Object.freeze({ id: 'ai-products', projectIds: Object.freeze(['interface-system']), href: '#case-interface-system', title: '文科生用 AI 做项目', summary: '从想法、界面到真机上跑起来' }),
    Object.freeze({ id: 'ai-workflows', projectIds: Object.freeze(['daily-insight', 'loki-health']), href: '#workflow', title: 'AI 工作流 / 个人系统', summary: '我怎么把每天的事留下来' }),
  ]),
  proofStrip: Object.freeze([
    Object.freeze({ projectId: 'interface-system', href: './projects/interface-system.html', title: '界面系统', image: './projects/assets/real/cola/cola-9skins-v5-overview.png', imageAlt: 'Cola 九套真实运行时皮肤总览', caption: '从三种方向试起，后来做到九套', imageWidth: 1112, imageHeight: 1190, imageFit: 'contain' }),
    Object.freeze({ projectId: 'perspective-distillation', href: './projects/perspective-distillation.html', title: '人物视角蒸馏', image: './projects/assets/real/perspective/liuyang-stage.jpg', imageAlt: '人物视角蒸馏使用的刘旸公开节目材料样本', caption: '每个判断都要能回到公开来源', imageWidth: 1080, imageHeight: 604, imageFit: 'cover' }),
    Object.freeze({ projectId: 'inkpanda', href: './projects/inkpanda.html', title: 'InkPanda', image: './projects/assets/real/inkpanda/outline.png', imageAlt: 'InkPanda 真实章节纲要界面', caption: '一部长篇被拆成小说、卷、章节和场景', imageWidth: 2000, imageHeight: 1114, imageFit: 'cover' }),
  ]),
  gearModules: Object.freeze([
    Object.freeze({ id: 'cola-skins', code: 'CASE-01', title: 'Cola 九套皮肤', readout: '我每天都要看它很久，就从三套代表方向试起，后来做到了九套，也让它记住上次的选择。', proof: '九套原型与真机运行画面', href: './projects/interface-system.html?room=cola', action: '看真实界面', image: './projects/assets/real/cola/inject-shot-1.png', tags: Object.freeze(['9 套原型', '真机运行', '选择记忆']) }),
    Object.freeze({ id: 'hub-skins', code: 'CASE-02', title: 'Loki Hub 十二套界面', readout: '同一批真实内容换了十二种界面。我逐套检查桌面阅读、手机顺序和切换动作。', proof: '十二套真实界面与桌面、移动端验收', href: './projects/interface-system.html?room=hub', action: '看真实页面', image: './projects/assets/real/hub/ui-selection-board.png', tags: Object.freeze(['12 套界面', '真实内容', '双端验收']) }),
    Object.freeze({ id: 'codex-theme', code: 'CASE-03', title: 'Codex 刘恋拼贴主题', readout: '背景图只是这套主题的起点。菜单、弹窗、任务卡、输入区和透明宠物，才是后来真正费工夫的地方。', proof: '主题组件方案；真实运行界面正在脱敏', href: './projects/interface-system.html?room=codex', action: '看改造过程', image: './projects/assets/exhibition/codex-liulian-cutout.webp', imageAlt: 'Codex 刘恋拼贴主题的公开人物视觉资产；不是完整运行界面', tags: Object.freeze(['任务卡', '对话框', '宠物分离']) }),
    Object.freeze({ id: 'daily-insight', code: 'CASE-04', title: '每日洞见 · unbook', readout: '我想坚持读两年书，又怕读完就忘，于是每天只留一个冲突、一个边界和一个问题。', proof: '四天真实洞见、四套工具与四个问题', href: './projects/daily-insight.html', action: '翻开四天记录', image: './projects/assets/exhibition/hub-real-verify-ui-body.webp', tags: Object.freeze(['Day 01—04', '洞见卡', '复习入口']) }),
    Object.freeze({ id: 'perspective', code: 'CASE-05', title: '人物视角蒸馏', readout: '我把公开材料拆开，看四个人遇到问题时先看什么、会怎么改，也把不知道的地方留着。', proof: '四个人物、公开证据与隔离留出评测', href: './projects/perspective-distillation.html', action: '进入四人工作区', image: './projects/assets/real/perspective/liulian-evidence-sheet-01.png', tags: Object.freeze(['刘恋', '刘旸', '鲁豫', 'Papi酱']) }),
    Object.freeze({ id: 'ebook', code: 'CASE-06', title: 'Loki 电子书转换器', readout: '把 Calibre 的复杂转换能力，做成不需要命令行的拖拽桌面工具。', proof: 'macOS 与 Windows 真实安装包', href: './projects/ebook-converter.html', action: '看产品怎么把复杂度藏起来', image: './projects/assets/real/ebook/app-home.png', tags: Object.freeze(['macOS 1.1.2', 'Windows 1.1.1', '批量转换']) }),
    Object.freeze({ id: 'inkpanda', code: 'CASE-07', title: 'InkPanda 长篇写作', readout: '写到第八十章，人物受过的伤和前面埋的伏笔很容易丢。我做了一个能替作者照看这些事的工作台。', proof: '首页、编辑器、纲要与发现页真实界面', href: './projects/inkpanda.html', action: '看真实产品与长篇判断', image: './projects/assets/real/inkpanda/editor.png', tags: Object.freeze(['长篇结构', '上下文记忆', '一致性检查']) }),
    Object.freeze({ id: 'lian', code: 'CASE-08', title: '恋之上上签', readout: '我从 44 首歌里手工挑了 147 条短句，还先给自己定下版权边界，再做抽签和卡片。', proof: '44 首歌、147 条精选短句与 16 套卡片视觉', href: './projects/lian.html', action: '看喜欢怎样变成作品', image: './projects/assets/real/lian/draw-result.jpg', tags: Object.freeze(['44 首歌', '147 条短句', '16 套视觉']) }),
  ]),
  skillCategories: Object.freeze([
    Object.freeze({ id: 'writing', order: 1, title: '写作与内容', note: '从一个念头、材料或旧稿，走到能继续发布和维护的内容。' }),
    Object.freeze({ id: 'visual', order: 2, title: '图像与视觉', note: '让信息先被看懂，再让它拥有属于 Loki 的视觉气质。' }),
    Object.freeze({ id: 'knowledge', order: 3, title: '研究与知识', note: '把划线、证据和人的判断整理成以后还能重新调用的东西。' }),
    Object.freeze({ id: 'building', order: 4, title: '程序与工具', note: '把复杂操作藏进更简单的入口，也把重复搭建写成可复用流程。' }),
    Object.freeze({ id: 'personal', order: 5, title: '个人创作', note: '从喜欢、身份和日常表达里长出来的长期实验。' }),
  ]),
  skillFlows: Object.freeze({
    'loki-writing': Object.freeze(['真实材料', '风格判断', '可发布长文']),
    'weixin-outline': Object.freeze(['模糊主题', '十个选题', '三段或五段大纲']),
    'deep-night': Object.freeze(['选题方向', '情感长文', '双平台 Markdown']),
    'weixin-layout': Object.freeze(['已经完成的正文', '层级与重点', '可复制发布稿']),
    headline: Object.freeze(['文章里的冲突', '信息差提炼', '标题候选']),
    'feishu-weixin': Object.freeze(['飞书成稿', '结构与格式转换', '公众号正文']),
    'long-writing-memory': Object.freeze(['当前章节', '召回相关记忆', '一致性提醒']),
    'film-poster': Object.freeze(['主题与情绪', '视觉构图', '电影字报']),
    'loki-social': Object.freeze(['长文论点', '卡片脚本', '多尺寸 PNG']),
    'visual-directions': Object.freeze(['视觉参考', '设计语言', '多方向方案']),
    'cover-system': Object.freeze(['文章核心', '封面信息层级', '21:9 与 1:1 封面对']),
    'image-kit': Object.freeze(['主题与约束', '中文提示词', '多比例图像']),
    slides: Object.freeze(['演示内容', '网页排版', '可直接演示页面']),
    book: Object.freeze(['原书或阅读材料', '冲突与边界', '一个思想实验']),
    notes: Object.freeze(['划线与批注', '主题聚合', '可复习笔记']),
    judgment: Object.freeze(['修改与选择证据', '判断模型', '留出题盲测']),
    debate: Object.freeze(['争论材料', '前提拆解', '真正分歧']),
    'self-mirror': Object.freeze(['日记与对话', '模式识别', '事实与推断分层']),
    'ai-radar': Object.freeze(['信息流', '影响筛选', '下一步行动']),
    'codex-theme': Object.freeze(['人物与视觉资产', '组件级改造', '可恢复主题']),
    'hatch-pet': Object.freeze(['角色图', '动画图集', 'v2 宠物包']),
    'skill-builder': Object.freeze(['一次做成的经验', '规则与边界', '可调用 Skill']),
    'prompt-spec': Object.freeze(['模糊需求', '条件与验收', '可执行说明']),
    'ebook-workflow': Object.freeze(['输入文件', '批量转换与进度', '可用电子书']),
    'cyber-red-panda': Object.freeze(['写作、视觉与日常', '一致的人格判断', '长期内容品牌']),
    'lian-curation': Object.freeze(['44 首歌', '147 条短句筛选', '抽签与 16 套卡片']),
    'collage-poem': Object.freeze(['当天的词句', '重新拼贴', '一首短诗']),
  }),
  skillGitHub: Object.freeze({
    'loki-writing': Object.freeze({ href: 'https://github.com/loki2046-mao', label: '打开 Loki 的 GitHub', kind: 'profile', note: '当前写作原型尚未单独公开仓库。' }),
    'weixin-outline': Object.freeze({ href: 'https://github.com/loki2046-mao/content-station', label: '查看相关公开项目', kind: 'related', note: '选题与大纲 Skill 尚未单独公开；这里展示公开的内容工作站。' }),
    'deep-night': Object.freeze({ href: 'https://github.com/loki2046-mao/cola-skills/tree/main/loki-wechat-pipeline', label: '查看相关公开工作流', kind: 'related', note: '深夜正文保留私密边界；这里展示公开的公众号写作与发布工作流。' }),
    'loki-social': Object.freeze({ href: 'https://github.com/loki2046-mao/cola-skills/tree/main/loki-social', label: '查看 Skill 源码', kind: 'source', note: '公开仓库包含模板、布局规则、渲染脚本与检查清单。' }),
    'visual-directions': Object.freeze({ href: 'https://github.com/loki2046-mao/cola-skills/tree/main/loki-design-system', label: '查看相关视觉系统', kind: 'related', note: '多方向方法尚未单独公开；这里展示公开的 Loki Design System。' }),
    notes: Object.freeze({ href: 'https://github.com/loki2046-mao', label: '打开 Loki 的 GitHub', kind: 'profile', note: '阅读笔记涉及私人材料，当前没有独立公开仓库。' }),
    judgment: Object.freeze({ href: 'https://github.com/loki2046-mao', label: '打开 Loki 的 GitHub', kind: 'profile', note: '判断蒸馏方法当前只公开展示脱敏证据，尚未单独发布源码。' }),
    'codex-theme': Object.freeze({ href: 'https://github.com/loki2046-mao', label: '打开 Loki 的 GitHub', kind: 'profile', note: '真实主题界面仍在脱敏，当前没有独立公开仓库。' }),
  }),
  skillVisuals: Object.freeze({
    'loki-writing': Object.freeze({ kind: 'process', motif: 'writing', caption: '工作路径图 / 真实材料怎样走到可发布长文' }),
    'weixin-outline': Object.freeze({ kind: 'process', motif: 'writing', caption: '选题与大纲路径 / 从模糊主题走到可写结构' }),
    'deep-night': Object.freeze({ kind: 'process', motif: 'writing', caption: '深夜写作路径 / 语气、长文与双平台格式' }),
    'weixin-layout': Object.freeze({ image: './projects/assets/exhibition/hub-real-ai-friends-body.webp', imageAlt: 'Loki Hub 已发布文章正文的真实排版', caption: '真实文章正文 / 层级、留白与阅读节奏', imageWidth: 1440, imageHeight: 1000, imageFit: 'contain' }),
    headline: Object.freeze({ kind: 'process', motif: 'writing', caption: '标题判断路径 / 从文章冲突里找到真正的信息差' }),
    'feishu-weixin': Object.freeze({ kind: 'process', motif: 'writing', caption: '格式迁移路径 / 保留结构，而不是重新排一遍' }),
    'long-writing-memory': Object.freeze({ image: './projects/assets/real/inkpanda/editor.png', imageAlt: 'InkPanda 真实编辑器，正文、人物与写作工具位于同一界面', caption: 'InkPanda 真实编辑器 / 写作、人物与前情在同一处', imageWidth: 2000, imageHeight: 1114, imageFit: 'contain' }),
    'film-poster': Object.freeze({ kind: 'process', motif: 'visual', caption: '字报设计路径 / 主题、构图和文字层级一起决定' }),
    'loki-social': Object.freeze({ image: './projects/assets/real/lian/card-style-2.jpg', imageAlt: '恋之上上签可保存分享的真实卡片样例', caption: '真实卡片成品 / 内容重新进入可保存的画面', imageWidth: 2000, imageHeight: 1407, imageFit: 'cover' }),
    'visual-directions': Object.freeze({ image: './projects/assets/exhibition/hub-ui-collage.webp', imageAlt: 'Loki Hub 多套真实界面方向拼贴', caption: '同一批真实内容 / 多种视觉方向并排比较', imageWidth: 1440, imageHeight: 1100, imageFit: 'contain' }),
    'cover-system': Object.freeze({ image: './projects/assets/exhibition/hub-article-room.webp', imageAlt: 'Loki Hub 文章封面系统的真实成品', caption: '真实文章封面 / 核心信息先于装饰', imageWidth: 1672, imageHeight: 941, imageFit: 'cover' }),
    'image-kit': Object.freeze({ image: './projects/assets/exhibition/perspective-stage-v1.webp', imageAlt: '人物视角蒸馏项目的原创舞台视觉', caption: '原创项目视觉 / 比例、场景、光线与用途一起定义', imageWidth: 1915, imageHeight: 821, imageFit: 'cover' }),
    slides: Object.freeze({ kind: 'process', motif: 'visual', caption: '网页演示路径 / 内容、排版与动效留在同一份文件' }),
    book: Object.freeze({ image: './projects/assets/exhibition/reading-desk-v1.webp', imageAlt: '每日洞见项目的原创阅读桌视觉', caption: '原创阅读桌 / 从一本书留下一个冲突、边界和问题', imageWidth: 1915, imageHeight: 821, imageFit: 'cover' }),
    notes: Object.freeze({ kind: 'process', motif: 'research', caption: '阅读笔记路径 / 先保留自己的划线、反对和疑问' }),
    judgment: Object.freeze({ image: './projects/assets/real/perspective/liulian-evidence-sheet-01.png', imageAlt: '刘恋公开节目材料的时间帧采样证据表', caption: '公开节目材料 / 人物判断先回到具体证据', imageWidth: 1940, imageHeight: 1186, imageFit: 'contain' }),
    debate: Object.freeze({ image: './projects/assets/real/perspective/liuyang-stage.jpg', imageAlt: '刘旸公开节目舞台材料', caption: '公开节目材料 / 从具体表达里拆前提和分歧', imageWidth: 1080, imageHeight: 604, imageFit: 'cover' }),
    'self-mirror': Object.freeze({ kind: 'process', motif: 'research', caption: '自我镜像路径 / 事实、反复出现的模式与推断分开摆放' }),
    'ai-radar': Object.freeze({ kind: 'process', motif: 'research', caption: '资讯筛选路径 / 最后必须落到自己的判断与行动' }),
    'codex-theme': Object.freeze({ image: './projects/assets/exhibition/codex-liulian-cutout.webp', imageAlt: 'Codex 刘恋拼贴主题的真实人物视觉资产', caption: '真实主题资产 / 人物气质继续进入组件与交互', imageWidth: 1535, imageHeight: 1024, imageFit: 'cover' }),
    'hatch-pet': Object.freeze({ image: './loki-ip-live.jpg', imageAlt: '赛博小熊猫 Loki 角色图', caption: '真实角色资产 / 从一张角色图走到可运行宠物', imageWidth: 640, imageHeight: 640, imageFit: 'contain' }),
    'skill-builder': Object.freeze({ kind: 'process', motif: 'building', caption: 'Skill 构建路径 / 经验、边界与验证一起留下' }),
    'prompt-spec': Object.freeze({ kind: 'process', motif: 'building', caption: '需求结构化路径 / 把模糊要求变成可检查条件' }),
    'ebook-workflow': Object.freeze({ image: './projects/assets/real/ebook/app-home.png', imageAlt: 'Loki 电子书转换器真实桌面界面', caption: '真实桌面工具 / 输入、转换与结果放进一个入口', imageWidth: 1280, imageHeight: 900, imageFit: 'contain' }),
    'cyber-red-panda': Object.freeze({ image: './loki-ip-live.jpg', imageAlt: '赛博小熊猫 Loki 的公开角色形象', caption: 'Loki 公开角色形象 / 写作、视觉与日常保持同一个人', imageWidth: 640, imageHeight: 640, imageFit: 'contain' }),
    'lian-curation': Object.freeze({ image: './projects/assets/real/lian/draw-result.jpg', imageAlt: '恋之上上签真实抽签结果和卡片画面', caption: '真实作品画面 / 44 首歌、147 条短句与卡片系统', imageWidth: 2000, imageHeight: 1407, imageFit: 'contain' }),
    'collage-poem': Object.freeze({ kind: 'process', motif: 'personal', caption: '拼贴诗路径 / 当天的词句只属于当天，不借用无关现场图' }),
  }),
  skillProfiles: Object.freeze({
    'loki-writing': Object.freeze({
      showcase: true, maturity: '早期原型', ownership: 'Loki 制作',
      origin: '我最初想让它先读我过去的文章，再把一堆聊天式的碎想法整理成稿。',
      trigger: '脑子里有很多材料，但还没有文章结构时。',
      judgment: '高频词不是风格，固定开头和固定结尾也不是我。',
      realResult: 'PDF 文本提取、短语统计、段落长度、标题与段落模板、Markdown 输出。',
      limitations: '写作部分仍大量依赖固定模板；我不会说它已经“学会了我的语气”。',
      evidenceStatus: '公开安全样例仍在准备，不借用已发布文章冒充输出。',
      visual: Object.freeze({ kind: 'process', motif: 'writing', caption: '真实材料、规则与输出仍需要分开核对' }),
    }),
    'weixin-outline': Object.freeze({
      showcase: true, maturity: '轻量 Skill', ownership: 'Loki 制作',
      origin: '我不想一有主题就硬写正文，先把它展开成真正不同的可能。',
      trigger: '只有主题、素材或一团想法，还不知道真正要写哪一篇时。',
      judgment: '不能为了点击率堆夸张词，也不能让十个标题只是同一句话换词。',
      realResult: '10 个选题，以及一份三段式或五段式的口语化大纲。',
      limitations: '规则清楚，但还没有长成独立工具。',
      evidenceStatus: '公开样例将按“主题 → 十个选题 → 选中一题 → 大纲”呈现。',
      visual: Object.freeze({ kind: 'process', motif: 'writing', caption: '先展开选择，再落到真正能写的结构' }),
    }),
    'deep-night': Object.freeze({
      showcase: true, maturity: 'Beta / 长期使用', ownership: 'Loki 制作',
      origin: '我不想每写完一篇情感文章，就再从 Obsidian 搬到公众号重新排一遍。',
      trigger: '从一个深夜情绪选题写成完整文章，并准备进入公众号时。',
      judgment: '颜色标签不等于情绪；所谓去 AI 味也不能只剩短段落与金句。',
      realResult: '1200—1500 字文章、标签、全角标点、图片位置、配图提示词和双平台格式。',
      limitations: '仍是 Beta；配图生成、广告位置和发布没有完全自动化。',
      evidenceStatus: '正文和笔记默认不公开；经同意后才展示脱敏的双平台对照。',
      visual: Object.freeze({ kind: 'process', motif: 'writing', caption: '双平台格式是真实能力，正文仍保留私密边界' }),
    }),
    'loki-social': Object.freeze({
      showcase: true, maturity: '完整生产方法', ownership: 'Loki 改造',
      origin: '不是把长文章塞进漂亮框里，而是先决定每张图让人一眼看懂什么。',
      trigger: '公众号封面对、小红书图文、产品解释卡和知识卡。',
      judgment: '证据图必须可看，中文信息层级先于配色和装饰。',
      realResult: '21:9、1:1、3:4 输出，12 类布局、HTML 模板、渲染与 QA。',
      limitations: '参考了通用生产逻辑，再以 Loki Design System 改造；不把它写成凭空原创。',
      evidenceStatus: '展示真实 21:9、1:1 与小红书输出。',
      visual: Object.freeze({ image: './projects/assets/real/skills/social-card-pair.png', imageAlt: '同一主题的 Loki 社交卡片 21:9 与 1:1 真实成品', caption: '同一内容 / 两种平台比例 / 真实输出', imageWidth: 2400, imageHeight: 1260, imageFit: 'contain' }),
    }),
    'visual-directions': Object.freeze({
      showcase: true, maturity: '完整生产方法', ownership: 'Loki 制作',
      origin: '同一份内容换颜色不算新风格；我想让不同方向真的改变阅读与使用方式。',
      trigger: '网站、卡片、海报或演示需要多个真正不同的视觉方向时。',
      judgment: '不能复制参考图的标志性资产，也不能拿同一模板换色凑数量。',
      realResult: '设计语言分析、3—9 个方向、跨媒介适配、选择板和桌面 / 移动端验收。',
      limitations: '每次选择仍需要人工判断，不能用“方向数量”冒充有效设计。',
      evidenceStatus: 'Loki Hub / Cola 的多方向界面可作为证据。',
      visual: Object.freeze({ image: './projects/assets/exhibition/hub-ui-collage.webp', imageAlt: 'Loki Hub 多套真实界面方向拼贴', caption: '同一批真实内容 / 多种结构并排比较', imageWidth: 1440, imageHeight: 1100, imageFit: 'contain' }),
    }),
    notes: Object.freeze({
      showcase: true, maturity: '长期使用', ownership: 'Loki 制作',
      origin: '我不想再得到一份“这本书讲了什么”的漂亮总结。',
      trigger: 'Apple Books 或 Obsidian 已积累大量划线，想整理成以后会再次调用的笔记时。',
      judgment: '不能用流畅总结覆盖原始批注；材料少时必须承认范围。',
      realResult: '划线提取、3—5 个主题、旧看法修正、行动项、复习点和未想透的问题。',
      limitations: '实际笔记默认属于私人材料，不以公开页面换取展示。',
      evidenceStatus: '没有公开授权时只展示规则与脱敏示意，不展示私人书摘和批注。',
      visual: Object.freeze({ kind: 'process', motif: 'research', caption: '先留下划线、反对和疑问，再整理为可复习笔记' }),
    }),
    judgment: Object.freeze({
      showcase: true, maturity: '完整生产方法', ownership: 'Loki 制作',
      origin: '我想保存的不是某个人常说什么，而是他在具体任务里会怎么选。',
      trigger: '从会议、修改记录、初稿终稿和操作日志里提炼个人或团队判断时。',
      judgment: '一次修改不能变成人格规律；语言像不等于判断像；推断要继续标成推断。',
      realResult: '来源清单、证据账本、判断模型、情境路由、目标 Skill 和留出评测。',
      limitations: '公开人物材料只能证明公开样本；对私人材料必须另行授权。',
      evidenceStatus: '刘恋公开节目时间帧证据表已就绪；判断账本只展示脱敏摘要。',
      visual: Object.freeze({ image: './projects/assets/real/perspective/liulian-evidence-sheet-01.png', imageAlt: '刘恋公开节目材料的时间帧采样证据表', caption: '公开材料先回到具体时间帧，再讨论判断', imageWidth: 1940, imageHeight: 1186, imageFit: 'contain' }),
    }),
    'codex-theme': Object.freeze({
      showcase: true, maturity: '完整生产方法', ownership: 'Loki 制作',
      origin: '我想改的不是颜色，而是让背景、人物、卡片、菜单、输入区、弹窗和宠物层真正成为同一套界面。',
      trigger: '为 Codex 制作带真实图片资产、组件规则和更新恢复能力的完整主题时。',
      judgment: '强视觉不能遮挡真实操作；静态人物和动画宠物必须分层；更新后不能在旧补丁上继续叠加。',
      realResult: '主题项目、组件装饰、干净备份、签名验证、更新检测与卸载路径。',
      limitations: '修改真实 App 仍需单独授权和实际 App 验收；公开预览先完成脱敏。',
      evidenceStatus: '真实桌面、首页、文件模式与移动端预览已找到，当前正在做公开裁切。',
      visual: Object.freeze({ kind: 'process', motif: 'building', caption: '真实主题预览正在脱敏；不再以人物剪影代替主题界面' }),
    }),
  }),
  skills: Object.freeze([
    Object.freeze({ id: 'loki-writing', category: 'writing', order: 1, title: 'Loki 写作助手', summary: '从真实材料和已有文章里学习语气，把杂乱想法整理成仍然像我会说的话。', tags: Object.freeze(['公众号', '风格', '长文']), form: '正式 Skill', visibility: 'public' }),
    Object.freeze({ id: 'weixin-outline', category: 'writing', order: 2, title: '公众号选题与大纲', summary: '先把一个模糊主题拆成可写的选题，再留下清楚但不公文化的文章骨架。', tags: Object.freeze(['选题', '大纲', '口语化']), form: '正式 Skill', visibility: 'public' }),
    Object.freeze({ id: 'deep-night', category: 'writing', order: 3, title: '深夜清醒 Writer', summary: '让同一份稿在 Obsidian 和公众号里都保留原来的气息、颜色和层级。', tags: Object.freeze(['情感写作', '双平台', '排版']), form: '正式 Skill', visibility: 'public' }),
    Object.freeze({ id: 'weixin-layout', category: 'writing', order: 4, title: '公众号排版', summary: '把已经写好的正文整理成可复制发布的节奏、层级与重点，而不是重新写一遍。', tags: Object.freeze(['发布', '层级', '复用']), form: '长期使用', visibility: 'public' }),
    Object.freeze({ id: 'headline', category: 'writing', order: 5, title: '微信标题生成', summary: '从文章真正的冲突和信息差里找标题，不靠夸张词制造虚假的点击。', tags: Object.freeze(['标题', '信息差', '分发']), form: '长期使用', visibility: 'public' }),
    Object.freeze({ id: 'feishu-weixin', category: 'writing', order: 6, title: '飞书转公众号', summary: '把飞书里的成稿带着结构搬进公众号，减少重复清格式和重新排版。', tags: Object.freeze(['飞书', '公众号', '发布']), form: '长期使用', visibility: 'public' }),
    Object.freeze({ id: 'long-writing-memory', category: 'writing', order: 7, title: '长篇写作记忆检查', summary: '在继续写之前找回人物、世界观、伏笔和时间线，避免第八十章忘了第八章。', tags: Object.freeze(['人物', '伏笔', '一致性']), form: '作品中沉淀', href: './projects/inkpanda.html', action: '看它怎样落进 InkPanda', visibility: 'public' }),

    Object.freeze({ id: 'film-poster', category: 'visual', order: 1, title: '电影字报生成器', summary: '把一个主题翻译成摄影质感、强字体排版和明确视觉焦点的电影字报。', tags: Object.freeze(['图像生成', '字报', '视觉设计']), form: '长期使用', visibility: 'public' }),
    Object.freeze({ id: 'loki-social', category: 'visual', order: 2, title: 'Loki 社交卡片', summary: '把文章重新组织成小红书图文、公众号封面对和有证据的知识卡片。', tags: Object.freeze(['小红书', '公众号封面', '知识卡片']), form: '正式 Skill', visibility: 'public' }),
    Object.freeze({ id: 'visual-directions', category: 'visual', order: 3, title: '多形态视觉系统', summary: '从参考里提取可以迁移的设计语言，再做成真正不同的网页、海报、卡片或演示方向。', tags: Object.freeze(['视觉分析', '多方向', '跨媒介']), form: '正式 Skill', visibility: 'public' }),
    Object.freeze({ id: 'cover-system', category: 'visual', order: 4, title: '封面设计系统', summary: '让封面承担文章入口，而不是只在正文前面放一张漂亮但没有信息的图。', tags: Object.freeze(['21:9', '1:1', '封面对']), form: '长期使用', visibility: 'public' }),
    Object.freeze({ id: 'image-kit', category: 'visual', order: 5, title: '生图套件', summary: '把比例、清晰度、构图、风格和用途写进同一套可直接生成的中文提示词。', tags: Object.freeze(['中文提示词', '多比例', '生成']), form: '长期使用', visibility: 'public' }),
    Object.freeze({ id: 'slides', category: 'visual', order: 6, title: '前端幻灯片', summary: '用网页做可以直接演示的页面，让排版、动效和内容在同一个文件里继续修改。', tags: Object.freeze(['演示', '网页', '动效']), form: '长期使用', visibility: 'public' }),

    Object.freeze({ id: 'book', category: 'knowledge', order: 1, title: '洞见型拆书', summary: '不追求把一本书复述完整，只留下最值得改变理解方式的冲突、边界和问题。', tags: Object.freeze(['书核', '认知冲突', '思想实验']), form: '长期使用', href: './projects/daily-insight.html', action: '看它怎样进入每日洞见', visibility: 'public' }),
    Object.freeze({ id: 'notes', category: 'knowledge', order: 2, title: '阅读笔记整理', summary: '优先保留自己的划线、反对和疑问，再整理成以后真的会回来看的笔记。', tags: Object.freeze(['划线', '批注', '复习']), form: '正式 Skill', href: './projects/daily-insight.html', action: '看公开样例', visibility: 'public' }),
    Object.freeze({ id: 'judgment', category: 'knowledge', order: 3, title: '工作判断蒸馏', summary: '从反复修改、拒绝和选择里找到稳定判断，再用没见过的新问题检查它会不会走样。', tags: Object.freeze(['证据账本', '情境路由', '盲测']), form: '正式 Skill', href: './projects/perspective-distillation.html', action: '看四个人物的公开证据', visibility: 'public' }),
    Object.freeze({ id: 'debate', category: 'knowledge', order: 4, title: '辩论思维提取', summary: '从一段争论里拆出双方前提、真正分歧和还没有被回答的问题。', tags: Object.freeze(['论点', '前提', '分歧']), form: '长期使用', visibility: 'public' }),
    Object.freeze({ id: 'self-mirror', category: 'knowledge', order: 5, title: '自我镜像', summary: '从日记、对话和选择里回看反复出现的模式，同时把事实和推断分开。', tags: Object.freeze(['复盘', '模式', '边界']), form: '长期使用', visibility: 'public' }),
    Object.freeze({ id: 'ai-radar', category: 'knowledge', order: 6, title: 'AI 新闻雷达', summary: '持续收集真正会影响工作方式的 AI 变化，再把资讯变成判断和下一步行动。', tags: Object.freeze(['资讯', '筛选', '行动']), form: '长期使用', visibility: 'public' }),

    Object.freeze({ id: 'codex-theme', category: 'building', order: 1, title: 'Codex 主题皮肤', summary: '把人物资产、组件规则、安装与更新恢复做成一套真正进入桌面 App 的主题流程。', tags: Object.freeze(['桌面 App', '组件', '恢复']), form: '正式 Skill', href: './projects/interface-system.html?room=codex', action: '看真实界面', visibility: 'public' }),
    Object.freeze({ id: 'hatch-pet', category: 'building', order: 2, title: 'Hatch Pet', summary: '从角色图出发，生成、检查并打包能够在 Codex 里真实运行的动画宠物。', tags: Object.freeze(['角色', '动画图集', '打包']), form: '正式 Skill', visibility: 'public' }),
    Object.freeze({ id: 'skill-builder', category: 'building', order: 3, title: 'Skill 构建与审阅', summary: '把一次做成的工作整理成触发清楚、边界明确、能够复用和验证的 Skill。', tags: Object.freeze(['封装', '审阅', '复用']), form: '长期使用', visibility: 'public' }),
    Object.freeze({ id: 'prompt-spec', category: 'building', order: 4, title: '需求与提示词结构化', summary: '把一句模糊需求补成条件、边界、验收和例子都清楚的可执行说明。', tags: Object.freeze(['需求', '提示词', '验收']), form: '正式 Skill', visibility: 'public' }),
    Object.freeze({ id: 'ebook-workflow', category: 'building', order: 5, title: '电子书转换工作流', summary: '把格式识别、批量转换、进度和失败反馈收进普通人能直接使用的入口。', tags: Object.freeze(['批量', '格式转换', '桌面工具']), form: '作品中沉淀', href: './projects/ebook-converter.html', action: '看它怎样变成桌面工具', visibility: 'public' }),

    Object.freeze({ id: 'cyber-red-panda', category: 'personal', order: 1, title: '赛博小熊猫 Loki', summary: '让长期写作、视觉和对外表达保持为同一个能被认出来、也能继续生长的人格。', tags: Object.freeze(['角色', '公众号', '视觉人格']), form: '长期使用', href: './about.html', action: '认识 Loki', visibility: 'public' }),
    Object.freeze({ id: 'lian-curation', category: 'personal', order: 2, title: '歌词答案书构建', summary: '从喜欢出发，自己筛选材料、划定版权边界，再把短句做成抽签与卡片。', tags: Object.freeze(['策展', '版权边界', '卡片']), form: '作品中沉淀', href: './projects/lian.html', action: '看恋之上上签', visibility: 'public' }),
    Object.freeze({ id: 'collage-poem', category: 'personal', order: 3, title: '每日拼贴诗', summary: '把当天留下来的词句和情绪重新拼接成一小块只属于那一天的文本。', tags: Object.freeze(['拼贴', '日常', '创作']), form: '长期使用', visibility: 'public' }),
  ]),
  projects: [
    {
      id: 'interface-system', date: '08-24', title: '个人化界面系统',
      summary: '我每天都要面对这些 AI 工具。前段时间从换颜色开始，后来一路改到菜单、弹窗、输入区和更新后的恢复。',
      tag: 'COLA × HUB × CODEX', href: './projects/interface-system.html',
      action: '看我怎么把它改到真机上', linkStatus: 'internal', visibility: 'public', group: 'flagship', order: 1,
      accent: '#ff6508', eyebrow: 'COLA × LOKI HUB × CODEX / 通用工具如何变成个人空间', anchor: 'case-interface-system',
      image: './projects/assets/real/cola/inject-shot-1.png',
      imageAlt: 'Cola 个性化界面真机运行截图',
      imageWidth: 2560, imageHeight: 1600, imageFit: 'cover',
      proof: '九套皮肤进入真实工具并记住选择。',
      status: '公开案例 · 真机界面已验证',
      verification: Object.freeze({ status: 'verified', checkedAt: '2026-08-28', scope: 'local-browser', note: '真机界面与本地案例页已核验' }),
    },
    {
      id: 'loki-ebook-converter', date: '08-11', title: 'Loki 电子书转换器',
      summary: '把 Calibre 强大但复杂的转换能力做成普通人可拖拽、批量处理、看见进度的桌面工具。',
      tag: 'MACOS 1.1.2 · WIN 1.1.1',
      href: './projects/ebook-converter.html',
      action: '看我如何把复杂能力做简单', linkStatus: 'internal', visibility: 'public', group: 'productization', order: 6,
      accent: '#ff397f', eyebrow: 'MACOS 1.1.2 × WINDOWS 1.1.1 / 把 Calibre 藏进拖拽入口',
      image: './projects/assets/real/ebook/app-home.png',
      imageAlt: 'Loki 电子书转换器真实桌面界面',
      imageWidth: 1280, imageHeight: 900, imageFit: 'cover',
      proof: '真实桌面应用界面；macOS 与 Windows 版本都已经做成可以安装的桌面工具。',
      status: '桌面工具已发布 · 可以下载',
      publicLink: Object.freeze({ href: 'https://github.com/loki2046-mao/loki-ebook-converter/releases/tag/v1.1.2', label: '前往下载页', status: 'verified', checkedAt: '2026-08-29' }),
      verification: Object.freeze({ status: 'verified', checkedAt: '2026-08-29', scope: 'release-page', note: '站内案例、Release 页面与 universal DMG 资产记录已复核；本轮未下载或安装 DMG' }),
    },
    {
      id: 'daily-insight', date: '08-25', title: '730 天每日洞见系统',
      summary: '我读完书常常记不住当时为什么被击中，于是每天留下一次冲突、一个边界和一个以后还想回答的问题。',
      tag: '阅读系统', href: './projects/daily-insight.html',
      action: '看我如何让长期目标运行', linkStatus: 'internal', visibility: 'public', group: 'workflow', order: 4,
      accent: '#eee5d5', eyebrow: '阅读 × 回看 × 长期记忆 / 每天留下一张未来会回来找我的卡',
      image: './projects/assets/exhibition/reading-desk-v1.webp',
      imageAlt: '每日洞见系统公开展台的视觉导览图',
      imageWidth: 1915, imageHeight: 821, imageFit: 'cover',
      proof: '视觉导览：730 天阅读系统的公开展台；四天洞见样例请进入案例页查看。',
      status: '公开案例 · 真实样例持续补充',
      systemKind: 'AI 阅读工作流',
      systemEvidence: Object.freeze([
        Object.freeze({ label: '每日动作', value: '从一本书留下一个冲突、边界和问题' }),
        Object.freeze({ label: '留下记录', value: '公开案例页已有四天洞见卡结构' }),
        Object.freeze({ label: '未来调用', value: '按日期回看，生成完以后还会再回来' }),
      ]),
      verification: Object.freeze({ status: 'pending', checkedAt: '2026-08-29', scope: 'local-browser', note: '案例页结构已核验，长期连续运行证据仍在补充' }),
    },
    {
      id: 'perspective-distillation', date: '08-25', title: '人物视角蒸馏',
      summary: '我喜欢看一个人遇到麻烦时先看什么、最后留下什么。公开材料被拆成证据，再拿没见过的新题检查判断会不会走样。',
      tag: 'NUWA 改造', href: './projects/perspective-distillation.html',
      action: '看我如何蒸馏隐性判断', linkStatus: 'internal', visibility: 'public', group: 'flagship', order: 2,
      accent: '#d7f43c', eyebrow: '公开证据 × 隔离评测 / 看判断动作能不能迁移',
      image: './projects/assets/real/perspective/liulian-evidence-sheet-01.png',
      imageAlt: '刘恋公开节目材料的时间帧采样',
      imageWidth: 1940, imageHeight: 1186, imageFit: 'contain',
      proof: '公开节目时间帧采样；完整来源、四人档案与隔离评测请进入案例页查看。',
      status: '研究型工作模型 · 内部评测',
      verification: Object.freeze({ status: 'verified', checkedAt: '2026-08-28', scope: 'local-browser', note: '公开材料证据表与内部评测页面已核验' }),
    },
    {
      id: 'loki-health', date: '08-22', title: "Loki's Health",
      summary: '围绕真实身体记录生长的本地优先健康 App；公开页只展示脱敏界面、产品判断与隐私边界。',
      tag: '我的身体节律', href: './projects/loki-health.html', action: '进入健康系统展台',
      linkStatus: 'internal', visibility: 'public', group: 'workflow', order: 5,
      accent: '#94d668', eyebrow: '本地优先 × 脱敏公开 / 让身体记录能够被照顾和回看',
      image: './projects/assets/real/health/today-desktop-redacted.png',
      imageAlt: "Loki's Health 本地真实产品的脱敏桌面截图",
      imageWidth: 1440, imageHeight: 1172, imageFit: 'contain',
      proof: '这些是脱敏后的真实产品画面；完整功能仍以实际产品体验为准。',
      status: '真实产品 · 展示内容已经脱敏',
      publicLink: Object.freeze({ href: 'https://lokihealthy.hiloki.ai/', label: '打开 Loki\'s Health', status: 'verified', checkedAt: '2026-08-29' }),
      systemKind: '个人记录系统（非 AI 核心）',
      systemEvidence: Object.freeze([
        Object.freeze({ label: '持续入口', value: '饮水、饮食、活动与身体目标集中记录' }),
        Object.freeze({ label: '留下记录', value: '只读同步与手动记录分开保存和回看' }),
        Object.freeze({ label: '公开边界', value: '仅展示脱敏截图，不公开真实健康数值' }),
      ]),
      verification: Object.freeze({ status: 'pending', checkedAt: '2026-08-29', scope: 'local-browser', note: '本地产品与脱敏素材已核验，公开入口 HTML 与核心资源已复核，具体交互待复核' }),
    },
    {
      id: 'inkpanda', date: '06-28', title: 'InkPanda · AI 长篇写作',
      summary: '写到后面，AI 会忘记人物受过的伤，也会漏掉早先的伏笔。作者继续写，系统负责把相关记忆找回来。',
      tag: '写作平台', href: './projects/inkpanda.html',
      action: '看真实产品与长篇判断', linkStatus: 'internal', visibility: 'public', group: 'flagship', order: 3,
      accent: '#d69a55', eyebrow: '上下文 × 记忆 × 一致性 / 让 AI 记住同一部长篇', anchor: 'case-inkpanda',
      image: './projects/assets/real/inkpanda/editor.png',
      imageAlt: 'InkPanda 真实编辑器界面',
      imageWidth: 2000, imageHeight: 1114, imageFit: 'cover',
      proof: '真实编辑器把正文、人物、前情和写作工具放在同一个长期空间里；完整体验需要登录。',
      status: '产品已经开放 · 完整体验需要登录',
      publicLink: Object.freeze({ href: 'https://inkxiaoxiongmao.hiloki.ai/', label: '打开 InkPanda', status: 'verified', checkedAt: '2026-08-29' }),
      verification: Object.freeze({ status: 'pending', checkedAt: '2026-08-29', scope: 'local-browser', note: '站内案例与真实界面已核验，公开入口 HTML 与核心资源已复核，登录后交互待复核' }),
    },
    {
      id: 'lian', date: '06-17', title: '恋之上上签',
      summary: '把对刘恋的喜欢做成一件有版权边界、视觉判断和真实交互的歌词答案书。',
      tag: '歌词答案书', href: './projects/lian.html',
      action: '看喜欢如何变成作品', linkStatus: 'internal', visibility: 'public', group: 'personal-practice', order: 7,
      accent: '#ffb53e', eyebrow: '私人喜欢 × 产品边界 / 44 首歌与 147 条精选短句',
      image: './projects/assets/real/lian/draw-result.jpg',
      imageAlt: '恋之上上签真实抽签结果页',
      imageWidth: 2000, imageHeight: 1407, imageFit: 'cover',
      proof: '历史抽签结果和 16 套卡片，留下了这件作品真实做出来时的样子。',
      status: '公开作品 · 入口可访问，抽签交互待复核',
      publicLink: Object.freeze({ href: 'https://lian.hiloki.ai/', label: '打开恋之上上签', status: 'verified', checkedAt: '2026-08-29' }),
      verification: Object.freeze({ status: 'pending', checkedAt: '2026-08-29', scope: 'local-browser', note: '站内案例与历史截图已核验，公开入口 HTML 与核心资源已复核，抽签交互待复核' }),
    },
  ],
});
