const {chromium}=require('/Users/kude/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('url');const path=require('path');const assert=require('assert/strict');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{for(const vp of [{width:1440,height:900},{width:390,height:844}]){
const p=await b.newPage({viewport:vp,reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.join(__dirname,'..','..','index.html')).href);await p.locator('#open-book').click();await p.waitForTimeout(100);await p.screenshot({path:`/tmp/book-about-${vp.width}.png`,animations:'disabled'});
await p.locator('.egg[popovertarget="supergirl"]').click();assert(await p.locator('#supergirl').isVisible());await p.screenshot({path:`/tmp/book-egg-${vp.width}.png`,animations:'disabled'});await p.keyboard.press('Escape');assert(!await p.locator('#supergirl').isVisible());
for(const role of ['writer','coder','audience']){await p.locator('[popovertarget="role-'+role+'"].identity-chip').click();assert(await p.locator('#role-'+role).isVisible());if(role==='writer'){await p.locator('#role-writer [data-wechat]').click();assert(await p.locator('#wechat-view').isVisible());await p.keyboard.press('Escape');}await p.screenshot({path:`/tmp/book-role-${role}-${vp.width}.png`,animations:'disabled'});await p.keyboard.press('Escape');}
const data=await p.evaluate(()=>({projects:bookData.projects.map(x=>x.id),skills:bookData.skills.map(x=>x.id)}));assert.equal(data.projects.length,7);assert.equal(data.skills.length,26);let tested=0;
for(const r of ['works',...['visual','writing','knowledge','building','personal'].map(x=>'skills-'+x),...data.projects.map(x=>'project-'+x),...data.skills.map(x=>'skill-'+x),'break']){await p.evaluate(r=>location.hash=r,r);await p.waitForTimeout(50);await p.locator('.right-page img:visible').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode())));const state=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,broken:[...document.images].filter(i=>i.offsetWidth&&(!i.complete||!i.naturalWidth)).map(i=>i.src)}));assert(!state.overflow,r+' overflow');assert.deepEqual(state.broken,[]);if(r.startsWith('skill-'))assert(await p.locator('#insert a[href^="https://github.com/"]').isVisible());if(r==='skills-visual')await p.screenshot({path:`/tmp/book-skills-${vp.width}.png`,animations:'disabled'});if(r.startsWith('skill-')){await p.locator('.pull-leaf:visible').click();assert(await p.locator('#method-leaf').isVisible());await p.locator('#method-leaf img:visible').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode())));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),r+' open overflow');await p.locator('.pull-leaf:visible').click()}tested++}
await p.locator('#cup-button').click();await p.waitForTimeout(100);assert(await p.locator('#cup-button').evaluate(e=>e.classList.contains('full')));for(const drink of ['green','oolong']){await p.locator(`[data-drink="${drink}"]`).click();await p.locator('#cup-button').click();await p.waitForTimeout(50);assert(await p.locator('#cup-button').evaluate(e=>e.classList.contains('full')))}await p.screenshot({path:`/tmp/book-break-${vp.width}.png`,animations:'disabled'});
await p.evaluate(()=>location.hash='works');await p.waitForTimeout(50);await p.screenshot({path:`/tmp/book-works-${vp.width}.png`,animations:'disabled'});await p.locator('.egg[popovertarget="sisters"]').click();assert.match(await p.locator('#sisters').textContent(),/刘恋/);assert.match(await p.locator('#sisters').textContent(),/万茜/);await p.keyboard.press('Escape');
await p.locator('.program-ticket[href="#project-lian"]').click();await p.waitForTimeout(50);await p.locator('.production-notes>summary').click();assert.match(await p.locator('.status-slip').textContent(),/抽签交互待复核/);await p.screenshot({path:`/tmp/book-lian-${vp.width}.png`,animations:'disabled'});await p.locator('[data-photo]').click();assert(await p.locator('#image-view').isVisible());await p.keyboard.press('Escape');await p.reload();assert(await p.locator('.project-heading').isVisible());await p.locator('#works-page .return').click();await p.locator('.program-tickets').waitFor({state:'visible'});assert(await p.locator('.program-tickets').isVisible());
assert.deepEqual(errors,[]);console.log(JSON.stringify({viewport:vp,routes:tested,errors,images:'loaded',overflow:false,drinks:'3 passed',popover:'passed',lightbox:'passed',hashReload:'passed'}));await p.close();
}}finally{await b.close()}})();
